# -*- mode: python ; coding: utf-8 -*-
"""
昆仑渗透测试平台 - PyInstaller 打包配置文件
===============================================
用途：将所有Python模块、依赖库、数据文件打包为单一可执行文件
支持：Windows 10/11, Linux (Ubuntu 20.04+/Debian 11+/CentOS 7+), macOS 11+
特性：
  - --onefile 单文件模式
  - 包含所有隐式导入模块
  - 包含Nuclei模板、证书目录、插件目录等数据文件
  - Windows UAC管理员权限支持
  - PyQt6 GUI完整支持
"""

import sys
import os
from pathlib import Path

# ==================== 基础配置 ====================
block_cipher = None

# 项目名称
PROJECT_NAME = "KunLun_PenTest"

# 主入口文件
main_script = 'main.py'

# ==================== 隐式导入模块声明 ====================
# 所有通过importlib动态加载、条件导入、字符串导入的模块必须在此声明
hidden_imports = [
    # PyQt6 核心模块
    'PyQt6',
    'PyQt6.QtCore',
    'PyQt6.QtGui',
    'PyQt6.QtWidgets',
    'PyQt6.QtNetwork',
    'PyQt6.QtWebEngineWidgets',
    'PyQt6.QtWebEngineCore',
    'PyQt6.QtWebChannel',
    'PyQt6.sip',
    'PyQt6.QtDBus',
    
    # 网络协议栈
    'aioquic',
    'aioquic.h0',
    'aioquic.h3',
    'aioquic.quic',
    'aioquic.tls',
    'aioquic.buffer',
    'aioquic.packet',
    'aioquic.packet_builder',
    'aioquic.quic_logger',
    'aioquic.recovery',
    'aioquic.retry',
    'dnslib',
    'dnslib.buffer',
    'dnslib.client',
    'dnslib.dns',
    'dnslib.fixedresolver',
    'dnslib.intercept',
    'dnslib.proxy',
    'dnslib.server',
    'scapy',
    'scapy.all',
    'scapy.layers',
    'scapy.layers.inet',
    'scapy.layers.inet6',
    'scapy.layers.dns',
    'scapy.layers.http',
    'scapy.layers.tls',
    'scapy.sendrecv',
    'scapy.utils',
    'pyshark',
    
    # 指纹识别
    'mmh3',
    'hashlib',
    'hmac',
    
    # JWT/OAuth/OIDC
    'jwt',
    'jwt.algorithms',
    'jwt.api_jwk',
    'jwt.api_jwt',
    'jwt.api_jws',
    'jwt.exceptions',
    'jwt.help',
    'jwt.jwk_set_cache',
    'jwt.utils',
    'cryptography',
    'cryptography.hazmat',
    'cryptography.hazmat.backends',
    'cryptography.hazmat.backends.openssl',
    'cryptography.hazmat.primitives',
    'cryptography.hazmat.primitives.asymmetric',
    'cryptography.hazmat.primitives.asymmetric.ec',
    'cryptography.hazmat.primitives.asymmetric.ed25519',
    'cryptography.hazmat.primitives.asymmetric.rsa',
    'cryptography.hazmat.primitives.ciphers',
    'cryptography.hazmat.primitives.ciphers.algorithms',
    'cryptography.hazmat.primitives.ciphers.modes',
    'cryptography.hazmat.primitives.hashes',
    'cryptography.hazmat.primitives.serialization',
    'cryptography.x509',
    'cryptography.x509.oid',
    'cryptography.x509.base',
    'cryptography.x509.extensions',
    'cryptography.x509.name',
    'OpenSSL',
    'OpenSSL.crypto',
    'OpenSSL.SSL',
    
    # GraphQL
    'graphql',
    'graphql.core',
    'graphql.language',
    'graphql.language.ast',
    'graphql.language.parser',
    'graphql.language.printer',
    'graphql.type',
    'graphql.type.definition',
    'graphql.type.schema',
    'graphql.validation',
    'graphql.validation.validate',
    'graphql.execution',
    'graphql.execution.execute',
    'graphql.error',
    'graphql.pyutils',
    'graphql.utilities',
    'graphql.utilities.build_ast_schema',
    'graphql.utilities.build_client_schema',
    'graphql.utilities.introspection_query',
    'graphql.utilities.print_schema',
    'graphql-core',
    
    # gRPC/Protobuf
    'google',
    'google.protobuf',
    'google.protobuf.descriptor',
    'google.protobuf.descriptor_pool',
    'google.protobuf.message',
    'google.protobuf.reflection',
    'google.protobuf.symbol_database',
    'google.protobuf.text_format',
    'google.protobuf.json_format',
    'grpc',
    'grpc.aio',
    'grpc.experimental',
    'grpc.framework',
    'grpc._cython',
    
    # Nuclei模板引擎
    'yaml',
    'ruamel.yaml',
    'jinja2',
    'jinja2.ext',
    'jinja2.utils',
    'jinja2.environment',
    'jinja2.loaders',
    'jinja2.runtime',
    'jinja2.compiler',
    'jinja2.nodes',
    'jinja2.optimizer',
    'jinja2.parser',
    'jinja2.lexer',
    'jinja2.filters',
    'jinja2.tests',
    'jinja2.async_utils',
    
    # 科学计算 (FID特征聚类)
    'numpy',
    'numpy.core',
    'numpy.core.multiarray',
    'numpy.core.umath',
    'numpy.linalg',
    'numpy.random',
    'numpy.random._pickle',
    'scipy',
    'scipy.sparse',
    'scipy.sparse.csgraph',
    'scipy.sparse.linalg',
    'scipy.special',
    'scipy.special._ufuncs_cxx',
    'sklearn',
    'sklearn.cluster',
    'sklearn.cluster._kmeans',
    'sklearn.cluster._dbscan',
    'sklearn.decomposition',
    'sklearn.decomposition._pca',
    'sklearn.metrics',
    'sklearn.metrics.pairwise',
    'sklearn.preprocessing',
    'sklearn.preprocessing._data',
    'sklearn.utils',
    'sklearn.utils._cython_blas',
    'sklearn.utils.extmath',
    'sklearn.utils.validation',
    'pandas',
    'pandas.core',
    'pandas.core.arrays',
    'pandas.core.arrays.sparse',
    'pandas.core.computation',
    'pandas.core.groupby',
    'pandas.core.indexes',
    'pandas.core.internals',
    'pandas.core.reshape',
    'pandas.core.strings',
    'pandas.core.tools',
    'pandas.io',
    'pandas.io.formats',
    'pandas.io.parsers',
    'pandas.tseries',
    'joblib',
    'joblib.externals',
    'joblib._multiprocessing_helpers',
    'threadpoolctl',
    
    # 异步IO
    'asyncio',
    'asyncio.events',
    'asyncio.base_events',
    'asyncio.tasks',
    'asyncio.locks',
    'asyncio.queues',
    'asyncio.streams',
    'asyncio.subprocess',
    'asyncio.unix_events',
    'asyncio.windows_events',
    'asyncio.windows_utils',
    'anyio',
    'anyio._backends',
    'anyio._backends._asyncio',
    'anyio._backends._trio',
    'trio',
    
    # 数据库
    'sqlite3',
    'sqlite3.dbapi2',
    'sqlalchemy',
    'sqlalchemy.dialects',
    'sqlalchemy.dialects.sqlite',
    'sqlalchemy.dialects.postgresql',
    'sqlalchemy.dialects.mysql',
    'sqlalchemy.orm',
    'sqlalchemy.ext',
    'sqlalchemy.ext.declarative',
    'alembic',
    'alembic.runtime',
    'alembic.runtime.migration',
    
    # 插件系统 (动态加载)
    'importlib',
    'importlib.util',
    'importlib.machinery',
    'importlib.abc',
    'pkgutil',
    'core.modules',
    'core.modules.base',
    'core.modules.event_bus',
    'core.modules.nuclei_executor',
    'core.modules.fingerprint',
    'core.modules.passive_scanner',
    'core.modules.attack_orchestrator',
    'core.modules.proxy',
    'core.modules.mitm',
    'core.modules.spider',
    'core.modules.portscan',
    'core.modules.space_engine',
    'core.modules.intruder',
    'core.modules.repeater',
    'core.modules.webfuzzer',
    'core.modules.reverseshell',
    'core.modules.poc',
    'core.modules.sequencer',
    'core.modules.decoder',
    'core.modules.comparer',
    'core.modules.codec',
    'core.modules.target',
    'core.modules.asset',
    'core.modules.vuln',
    'core.modules.poc_verify',
    'core.modules.plugin_mgmt',
    'core.modules.pluginstore',
    'core.modules.yakrunner',
    'core.modules.ai_security',
    'core.modules.knowledge_base',
    'core.modules.report',
    'core.modules.mitm_advanced',
    'core.modules.mitm_proxy_engine',
    'core.modules.mitm_advanced_features',
    'core.modules.mitm_script_extension',
    'core.modules.mitm_passive_scanner',
    'core.modules.mitm_replay_engine',
    'core.modules.mitm_adaptive_protocol',
    'core.modules.mitm_security_hardening',
    'core.modules.mitm_network_simulation',
    'core.modules.mitm_mock_response',
    'core.modules.mitm_advanced_filter',
    'core.modules.mitm_app_integration',
    'core.modules.mitm_asset_linkage',
    'core.modules.deser_integration',
    'core.modules.deserialization_exploit',
    'core.modules.deser_parser',
    'core.modules.deser_sandbox',
    'core.modules.java_deser_detector',
    'core.modules.gadget_chain_manager',
    'core.modules.jndi_bypass',
    'core.modules.java_ecosystem',
    'core.modules.deser_attack_pipeline',
    'core.modules.deser_knowledge_base',
    'core.modules.deser_community',
    'core.modules.deser_report',
    'core.modules.mem_shell_generator',
    'core.modules.payload_generator',
    'core.modules.payload_obfuscator',
    'core.modules.graphql_integration',
    'core.modules.graphql_attacks',
    'core.modules.graphql_advanced_attacks',
    'core.modules.graphql_detector',
    'core.modules.graphql_introspector',
    'core.modules.graphql_authz_tester',
    'core.modules.graphql_jwt_test',
    'core.modules.graphql_subscription_test',
    'core.modules.graphql_attack_pipeline',
    'core.modules.graphql_deep_injection',
    'core.modules.graphql_enterprise',
    'core.modules.graphql_platform_integration',
    'core.modules.grpc_integration',
    'core.modules.grpc_parser',
    'core.modules.grpc_repeater',
    'core.modules.grpc_exploit',
    'core.modules.jwt_editor',
    'core.modules.jwt_advanced_attacks',
    'core.modules.jwt_attack_orchestration',
    'core.modules.jwt_diagnostic_ai',
    'core.modules.jwt_info_leak',
    'core.modules.jwt_obfuscation',
    'core.modules.jwt_oauth_integration',
    'core.modules.jwt_oauth_passive_rules',
    'core.modules.jwt_oauth_poc_gen',
    'core.modules.jwt_oauth_scenarios',
    'core.modules.oauth_analyzer',
    'core.modules.oauth_deep_test',
    'core.modules.oauth_cross_client',
    'core.modules.oidc_analyzer',
    'core.modules.oidc_deep_exploit',
    'core.modules.cross_protocol_token',
    'core.modules.jwt_parser_exploits',
    'core.modules.domain_attack_integration',
    'core.modules.domain_attack_panel',
    'core.modules.domain_decision_engine',
    'core.modules.domain_privesc',
    'core.modules.domain_auto_explore',
    'core.modules.domain_stealth',
    'core.modules.domain_persistence_recovery',
    'core.modules.domain_self_test',
    'core.modules.adcs_escalation',
    'core.modules.dcsync_attack',
    'core.modules.dcshadow',
    'core.modules.gpo_backdoor',
    'core.modules.dsrm_backdoor',
    'core.modules.adminsdholder',
    'core.modules.cross_domain_trust',
    'core.modules.cross_forest_exploit',
    'core.modules.beacon_lifecycle',
    'core.modules.beacon_profile_adapter',
    'core.modules.channel_manager',
    'core.modules.domain_fronting',
    'core.modules.malleable_profile',
    'core.modules.dga_generator',
    'core.modules.extreme_comms',
    'core.modules.hibernation',
    'core.modules.memory_encryption',
    'core.modules.evasion_tester',
    'core.modules.genetic_profile_engine',
    'core.modules.ai_traffic_gan',
    'core.modules.digital_twin_sim',
    'core.modules.cognitive_warfare',
    'core.modules.blockchain_c2',
    'core.modules.p2p_mesh',
    'core.modules.kernel_beacon',
    'core.modules.pqc_crypto',
    'core.modules.self_destruct',
    'core.modules.self_healing_c2',
    'core.modules.swarm_intelligence',
    'core.modules.supply_chain_hijack',
    'core.modules.siem_evasion',
    'core.modules.polymorphic_engine',
    'core.modules.process_mask',
    'core.modules.profile_generator',
    'core.modules.profile_ide',
    'core.modules.profile_marketplace',
    'core.modules.profile_tester',
    'core.modules.privesc_exploit_engine',
    'core.modules.privesc_decision_tree',
    'core.modules.privesc_report',
    'core.modules.privesc_arsenal',
    'core.modules.privesc_evasion',
    'core.modules.privesc_rl_agent',
    'core.modules.privesc_graph',
    'core.modules.privesc_audit',
    'core.modules.cloud_privesc',
    'core.modules.knowledge_base_module',
    'core.modules.poc_research',
    'core.modules.privesc_stealth',
    'core.modules.privesc_self_healing',
    'core.modules.privesc_cross_platform',
    'core.modules.privesc_scheduler',
    'core.modules.privesc_self_test',
    'core.modules.privesc_observability',
    'core.modules.privesc_config',
    'core.modules.ai_engine',
    'core.modules.ai_conversation',
    'core.modules.ai_learning',
    'core.modules.ai_report',
    'core.modules.ai_penetration_test',
    'core.modules.collab_integration',
    'core.modules.collab_project',
    'core.modules.collab_task',
    'core.modules.collab_chat',
    'core.modules.collab_dashboard',
    'core.modules.collab_timeline',
    'core.modules.collab_sharing',
    'core.modules.collab_audit',
    'core.modules.cluster_manager',
    'core.modules.cluster_integration',
    'core.modules.cluster_master',
    'core.modules.cluster_worker',
    'core.modules.cluster_communication',
    'core.modules.federation_integration',
    'core.modules.federation_protocol',
    'core.modules.federation_security',
    'core.modules.federation_sync',
    'core.modules.federation_offline',
    'core.modules.federation_cdn_p2p',
    'core.modules.federation_registry',
    'core.modules.iot_modbus_scanner',
    'core.modules.iot_coap_scanner',
    'core.modules.iot_mqtt_scanner',
    'core.modules.knowledge_graph_integration',
    'core.modules.knowledge_graph_builder',
    'core.modules.knowledge_graph_query',
    'core.modules.knowledge_graph_model',
    'core.modules.knowledge_graph_snapshot',
    'core.modules.knowledge_graph_visualizer',
    'core.modules.export_manager',
    'core.modules.export_integration',
    'core.modules.har_exporter',
    'core.modules.pcap_exporter',
    'core.modules.enterprise_integration',
    'core.modules.enterprise_template_manager',
    'core.modules.attack_chain_template',
    'core.modules.attck_integration',
    'core.modules.attck_mapper',
    'core.modules.attck_visualizer',
    'core.modules.attck_techniques_db',
    'core.modules.learning_path',
    'core.modules.oob_detector',
    'core.modules.mobile_apk_parser',
    'core.modules.mobile_ipa_parser',
    'core.modules.mobile_sensitive_detector',
    'core.modules.mobile_iot_integration',
    'core.modules.asset_manager',
    'core.modules.extender',
    'core.modules.fingerprint_matcher',
    'core.modules.mitm_diagnostics',
    'core.modules.mitm_fuzzer_integration',
    'core.modules.mitm_h2_advanced',
    'core.modules.mitm_h3_advanced',
    'core.modules.mitm_lateral_movement',
    'core.modules.mitm_mobile_support',
    'core.modules.mitm_performance',
    'core.modules.mitm_protocol_negotiator',
    'core.modules.mitm_replay_fuzzer',
    'core.modules.mitm_reverse_integration',
    'core.modules.mitm_reverse_linkage',
    'core.modules.mitm_security',
    'core.modules.mitm_security_audit',
    'core.modules.mitm_traffic_collaboration',
    'core.modules.mitm_vuln_linkage',
    'core.modules.nuclei_helpers',
    'core.modules.nuclei_models',
    'core.modules.plugin_debugger',
    'core.modules.plugin_dependency',
    'core.modules.plugin_engine',
    'core.modules.plugin_management_ui',
    'core.modules.plugin_manager',
    'core.modules.plugin_market',
    'core.modules.plugin_market_ops',
    'core.modules.plugin_sandbox',
    'core.modules.plugin_security',
    'core.modules.poc_engine',
    'core.modules.poc_verification_manager',
    'core.modules.poc_verification_ui',
    'core.modules.protobuf_decoder',
    'core.modules.protobuf_schema',
    'core.modules.quic_connection_pool',
    'core.modules.quic_protocol',
    'core.modules.quic_tls',
    'core.modules.range_deployer',
    'core.modules.range_integration',
    'core.modules.range_manager',
    'core.modules.rasp_waf_bypass',
    'core.modules.report_generator',
    'core.modules.result_models',
    'core.modules.sandbox_executor',
    'core.modules.scanner',
    'core.modules.session_mfa_bypass',
    'core.modules.shadow_credentials',
    'core.modules.shiro_exploit',
    'core.modules.skeleton_key',
    'core.modules.skill_evaluator',
    'core.modules.ssp_backdoor',
    'core.modules.template_ai_generator',
    'core.modules.template_analytics',
    'core.modules.template_audit',
    'core.modules.template_commerce',
    'core.modules.template_editor',
    'core.modules.template_executor',
    'core.modules.template_incentive',
    'core.modules.template_integration',
    'core.modules.template_marketplace',
    'core.modules.template_recorder',
    'core.modules.template_replay',
    'core.modules.template_validator',
    'core.modules.test_ai_security',
    'core.modules.threat_intel',
    'core.modules.tls_fingerprint',
    'core.modules.token_lifecycle',
    'core.modules.traffic_engine',
    'core.modules.traffic_learner',
    'core.modules.updater_checker',
    'core.modules.updater_downloader',
    'core.modules.updater_installer',
    'core.modules.updater_plugin',
    'core.modules.updater_ui',
    'core.modules.updater_version',
    'core.modules.vuln_manager',
    'core.modules.weblogic_exploit',
    'core.modules.wireless_ble_scanner',
    'core.modules.workflow_editor',
    'core.modules.workflow_engine',
    'core.modules.http3_proxy',
    'core.modules.http3_frames',
    'core.modules.mitm_h2_engine',
    'core.modules.mitm_h3_engine',
    'core.modules.mitm_replay_fuzzer',
    'core.modules.mitm_performance',
    'core.modules.mitm_protocol_negotiator',
    'core.modules.mitm_security',
    'core.modules.mitm_diagnostics',
    'core.modules.mitm_traffic_collaboration',
    'core.modules.mitm_reverse_linkage',
    'core.modules.mitm_reverse_integration',
    'core.modules.mitm_lateral_movement',
    'core.modules.mitm_c2_linkage',
    'core.modules.mitm_vuln_linkage',
    'core.modules.mitm_asset_linkage',
    'core.modules.mitm_security_audit',
    'core.modules.mitm_mobile_support',
    'core.modules.mitm_fuzzer_integration',
    'core.modules.c2_automation',
    'core.modules.c2_observability',
    
    # 其他依赖
    'certifi',
    'chardet',
    'charset_normalizer',
    'idna',
    'urllib3',
    'requests',
    'requests.adapters',
    'requests.auth',
    'requests.cookies',
    'requests.exceptions',
    'requests.models',
    'requests.sessions',
    'requests.structures',
    'requests.utils',
    'requests.packages',
    'requests.packages.urllib3',
    'aiohttp',
    'aiohttp.client',
    'aiohttp.web',
    'aiohttp.web_runner',
    'aiohttp.web_protocol',
    'aiohttp.connector',
    'aiohttp.client_reqrep',
    'aiohttp.http',
    'aiohttp.http_parser',
    'aiohttp.http_writer',
    'aiohttp.tcp_helpers',
    'aiohttp.helpers',
    'aiohttp.abc',
    'aiohttp.log',
    'aiohttp.streams',
    'aiohttp.payload',
    'aiohttp.formdata',
    'aiohttp.multipart',
    'aiohttp.client_exceptions',
    'aiohttp.client_ws',
    'aiohttp.web_ws',
    'aiohttp.web_request',
    'aiohttp.web_response',
    'aiohttp.web_exceptions',
    'aiohttp.web_urldispatcher',
    'aiohttp.web_app',
    'aiohttp.web_middlewares',
    'aiohttp.web_server',
    'aiohttp.base_protocol',
    'aiohttp.locks',
    'aiohttp.typedefs',
    'aiosignal',
    'frozenlist',
    'multidict',
    'yarl',
    'async_timeout',
    'httpx',
    'httpcore',
    'sniffio',
    'h11',
    'h2',
    'hpack',
    'hyperframe',
    'wsproto',
    'websockets',
    'websockets.legacy',
    'websockets.frames',
    'websockets.protocol',
    'websockets.asyncio',
    'websockets.datastructures',
    'websockets.exceptions',
    'websockets.extensions',
    'websockets.extensions.base',
    'websockets.extensions.permessage_deflate',
    'websockets.headers',
    'websockets.http',
    'websockets.http11',
    'websockets.imports',
    'websockets.legacy.async_timeout',
    'websockets.legacy.auth',
    'websockets.legacy.client',
    'websockets.legacy.compatibility',
    'websockets.legacy.framing',
    'websockets.legacy.handshake',
    'websockets.legacy.http',
    'websockets.legacy.protocol',
    'websockets.legacy.server',
    'websockets.sync',
    'websockets.sync.client',
    'websockets.sync.connection',
    'websockets.sync.messages',
    'websockets.sync.server',
    'websockets.sync.utils',
    'websockets.uri',
    'websockets.utils',
    'websockets.version',
    
    # 数据处理
    'json',
    'json.decoder',
    'json.encoder',
    'json.scanner',
    'csv',
    'csv Dialect',
    'xml',
    'xml.etree',
    'xml.etree.ElementTree',
    'xml.parsers',
    'xml.parsers.expat',
    'html',
    'html.parser',
    'html.entities',
    'email',
    'email.parser',
    'email.message',
    'email.header',
    'email.utils',
    'email.policy',
    'email.mime',
    'email.mime.text',
    'email.mime.multipart',
    'email.mime.base',
    'email.mime.application',
    'email.mime.image',
    'email.mime.audio',
    'email.mime.nonmultipart',
    'email.charset',
    'email.encoders',
    'email.errors',
    'email.feedparser',
    'email.generator',
    'email.headerregistry',
    'email.iterators',
    'email._policybase',
    
    # 系统工具
    'subprocess',
    'multiprocessing',
    'multiprocessing.spawn',
    'multiprocessing.popen_spawn_win32',
    'multiprocessing.popen_spawn_posix',
    'multiprocessing.popen_fork',
    'multiprocessing.popen_forkserver',
    'multiprocessing.connection',
    'multiprocessing.reduction',
    'multiprocessing.shared_memory',
    'concurrent',
    'concurrent.futures',
    'concurrent.futures.thread',
    'concurrent.futures.process',
    'threading',
    'queue',
    'logging',
    'logging.handlers',
    'logging.config',
    'tempfile',
    'shutil',
    'pathlib',
    'glob',
    'fnmatch',
    'stat',
    'struct',
    'ctypes',
    'ctypes.util',
    'platform',
    'socket',
    'ssl',
    'select',
    'selectors',
    'signal',
    'time',
    'datetime',
    'calendar',
    'collections',
    'collections.abc',
    'itertools',
    'functools',
    'operator',
    'copy',
    'copyreg',
    'pickle',
    'pickletools',
    'pprint',
    're',
    'string',
    'textwrap',
    'unicodedata',
    'base64',
    'binascii',
    'hashlib',
    'hmac',
    'secrets',
    'uuid',
    'dataclasses',
    'typing',
    'typing_extensions',
    'enum',
    'abc',
    'io',
    'os',
    'sys',
    'builtins',
    'warnings',
    'contextlib',
    'inspect',
    'dis',
    'token',
    'tokenize',
    'ast',
    'symtable',
    'compileall',
    'py_compile',
    'zipimport',
    'zipfile',
    'lzma',
    'bz2',
    'gzip',
    'zlib',
    'tarfile',
    'argparse',
    'getopt',
    'getpass',
    'curses',
    'readline',
    'rlcompleter',
    'code',
    'codeop',
    'codecs',
    'locale',
    'gettext',
    'decimal',
    'fractions',
    'cmath',
    'math',
    'random',
    'statistics',
    'array',
    'bisect',
    'heapq',
    'weakref',
    'types',
    'pprint',
    'reprlib',
    'numbers',
    'atexit',
    'traceback',
    'linecache',
    'trace',
    'gc',
    'site',
    'sysconfig',
    'distutils',
    'distutils.util',
    'pkg_resources',
    'setuptools',
    'setuptools._vendor',
    'setuptools._vendor.packaging',
    'setuptools._vendor.packaging.version',
    'setuptools._vendor.packaging.specifiers',
    'setuptools._vendor.packaging.requirements',
    'setuptools._vendor.packaging.markers',
    'setuptools._vendor.packaging.utils',
    'setuptools._vendor.packaging.tags',
    'setuptools._vendor.packaging._manylinux',
    'setuptools._vendor.packaging._musllinux',
    'setuptools._vendor.pyparsing',
    'setuptools.extern',
    'pkg_resources.extern',
    'pkg_resources._vendor',
    'pkg_resources._vendor.packaging',
    'pkg_resources._vendor.pyparsing',
    'pkg_resources._vendor.appdirs',
    
    # 网络工具
    'ipaddress',
    'netifaces',
    'psutil',
    'psutil._psutil_windows',
    'psutil._psutil_linux',
    'psutil._psutil_osx',
    'psutil._psposix',
    'psutil._pswindows',
    'psutil._pslinux',
    'psutil._psosx',
    
    # 加密相关
    'nacl',
    'nacl.bindings',
    'nacl.exceptions',
    'nacl.encoding',
    'nacl.hash',
    'nacl.hashlib',
    'nacl.public',
    'nacl.secret',
    'nacl.signing',
    'nacl.utils',
    'paramiko',
    'paramiko.transport',
    'paramiko.client',
    'paramiko.ssh_exception',
    'paramiko.auth_handler',
    'paramiko.channel',
    'paramiko.kex_group1',
    'paramiko.kex_group14',
    'paramiko.kex_group16',
    'paramiko.kex_gex',
    'paramiko.kex_curve25519',
    'paramiko.message',
    'paramiko.packet',
    'paramiko.pkey',
    'paramiko.rsakey',
    'paramiko.dsskey',
    'paramiko.ecdsakey',
    'paramiko.ed25519key',
    'paramiko.sftp',
    'paramiko.sftp_client',
    'paramiko.sftp_file',
    'paramiko.sftp_attr',
    'paramiko.sftp_si',
    'paramiko.server',
    'paramiko.util',
    'paramiko.agent',
    'paramiko.ber',
    'paramiko.hostkeys',
    'paramiko.primes',
    'paramiko.py3compat',
    'paramiko.win_pageant',
    'bcrypt',
    'nacl',
    'cffi',
    'cffi.api',
    'cffi.backend',
    'cffi.cparser',
    'cffi.lock',
    'cffi.vengine_cpy',
    'cffi.vengine_gen',
    'cffi.verifier',
    'cffi.model',
    'cffi.error',
    'pycparser',
    'pycparser.c_parser',
    'pycparser.c_ast',
    'pycparser.c_lexer',
    'pycparser.ply',
    'pycparser.ply.lex',
    'pycparser.ply.yacc',
    
    # 报告生成
    'pdfkit',
    'weasyprint',
    'weasyprint.text',
    'weasyprint.formatting_structure',
    'weasyprint.layout',
    'weasyprint.draw',
    'weasyprint.pdf',
    'jinja2',
    'jinja2.ext',
    'jinja2.utils',
    'jinja2.environment',
    'jinja2.loaders',
    'jinja2.runtime',
    'jinja2.compiler',
    'jinja2.nodes',
    'jinja2.optimizer',
    'jinja2.parser',
    'jinja2.lexer',
    'jinja2.filters',
    'jinja2.tests',
    'jinja2.async_utils',
    'markdown',
    'markdown.extensions',
    'markdown.extensions.extra',
    'markdown.extensions.tables',
    'markdown.extensions.fenced_code',
    'markdown.extensions.codehilite',
    'markdown.extensions.toc',
    'markdown.extensions.meta',
    'markdown.extensions.attr_list',
    'markdown.extensions.def_list',
    'markdown.extensions.footnotes',
    'markdown.extensions.abbr',
    'markdown.extensions.smarty',
    'markdown.extensions.wikilinks',
    'markdown.extensions.admonition',
    'markdown.extensions.sane_lists',
    'markdown.extensions.nl2br',
    'markdown.extensions.md_in_html',
    'markdown.extensions.legacy_attrs',
    'markdown.extensions.legacy_em',
    'markdown.inlinepatterns',
    'markdown.blockprocessors',
    'markdown.blockparser',
    'markdown.treeprocessors',
    'markdown.postprocessors',
    'markdown.preprocessors',
    'markdown.util',
    'markdown.core',
    'markdown.htmlparser',
    'markdown.htmlparser',
    
    # 其他
    'colorama',
    'colorama.initialise',
    'colorama.ansitowin32',
    'colorama.win32',
    'colorama.winterm',
    'colorama.ansi',
    'tqdm',
    'tqdm.std',
    'tqdm.auto',
    'tqdm.notebook',
    'tqdm.gui',
    'rich',
    'rich.console',
    'rich.text',
    'rich.panel',
    'rich.table',
    'rich.columns',
    'rich.progress',
    'rich.status',
    'rich.spinner',
    'rich.rule',
    'rich.box',
    'rich.align',
    'rich.style',
    'rich.theme',
    'rich.highlighter',
    'rich.markup',
    'rich.segment',
    'rich.cells',
    'rich.padding',
    'rich.measure',
    'rich.protocol',
    'rich.repr',
    'rich.errors',
    'rich.emoji',
    'rich.markdown',
    'rich.syntax',
    'rich.traceback',
    'rich.logging',
    'rich.pretty',
    'rich.json',
    'rich.prompt',
    'rich.confirm',
    'rich.live',
    'rich.screen',
    'rich.layout',
    'rich.containers',
    'rich.control',
    'rich.constrain',
    'rich.file_proxy',
    'rich._log_render',
    'rich._loop',
    'rich._palettes',
    'rich._pick',
    'rich._ratio',
    'rich._spinners',
    'rich._stack',
    'rich._timer',
    'rich._win32_console',
    'rich._windows',
    'rich._windows_renderer',
    'rich._wrap',
    'pygments',
    'pygments.lexers',
    'pygments.lexers.python',
    'pygments.lexers.web',
    'pygments.lexers.templates',
    'pygments.lexers.javascript',
    'pygments.lexers.css',
    'pygments.lexers.html',
    'pygments.lexers.markup',
    'pygments.lexers.data',
    'pygments.lexers.graphql',
    'pygments.lexers.protobuf',
    'pygments.styles',
    'pygments.styles.default',
    'pygments.formatters',
    'pygments.formatters.html',
    'pygments.formatters.terminal',
    'pygments.formatters.terminal256',
    'pygments.token',
    'pygments.util',
    'pygments.regexopt',
    'pygments.plugin',
    'pygments.filter',
    'pygments.filters',
    'pygments.style',
    'pygments.console',
    'pygments.cmdline',
    'pygments.unistring',
    'pygments.scanner',
    'dateutil',
    'dateutil.parser',
    'dateutil.tz',
    'dateutil.relativedelta',
    'dateutil.rrule',
    'dateutil.easter',
    'dateutil.zoneinfo',
    'six',
    'pytz',
    'pytz.exceptions',
    'pytz.lazy',
    'pytz.tzinfo',
    'pytz.tzfile',
    'appdirs',
    'platformdirs',
    'xdg',
    'xdg.BaseDirectory',
    'toml',
    'tomli',
    'tomli_w',
    'pydantic',
    'pydantic.fields',
    'pydantic.main',
    'pydantic.types',
    'pydantic.validators',
    'pydantic.networks',
    'pydantic.datetime_parse',
    'pydantic.error_wrappers',
    'pydantic.utils',
    'pydantic.color',
    'pydantic.json',
    'pydantic.schema',
    'pydantic.tools',
    'pydantic.parse',
    'pydantic.env_settings',
    'pydantic.decorator',
    'pydantic.generics',
    'pydantic.dataclasses',
    'pydantic.class_validators',
    'pydantic.version',
    'pydantic.typing',
    'pydantic.errors',
    'pydantic.mypy',
    'pydantic._internal',
    'pydantic._internal._decorators',
    'pydantic._internal._fields',
    'pydantic._internal._generate_schema',
    'pydantic._internal._generics',
    'pydantic._internal._model_construction',
    'pydantic._internal._repr',
    'pydantic._internal._schema_generation',
    'pydantic._internal._std_types_schema',
    'pydantic._internal._typing_extra',
    'pydantic._internal._utils',
    'pydantic._internal._validate_call',
    'pydantic_core',
    'pydantic_core.core_schema',
    'annotated_types',
    'typing_inspect',
    'email_validator',
    'email_validator.validate_email',
    'email_validator.exceptions',
    'email_validator.types',
    'email_validator.deliverability',
    'email_validator.rfc_constants',
    'email_validator.syntax',
    'dnspython',
    'dnspython.dns',
    'dnspython.resolver',
    'dnspython.reversename',
    'dnspython.name',
    'dnspython.rdata',
    'dnspython.rdtypes',
    'dnspython.rdtypes.IN',
    'dnspython.rdtypes.ANY',
    'dnspython.rrset',
    'dnspython.zone',
    'dnspython.update',
    'dnspython.query',
    'dnspython.message',
    'dnspython.flags',
    'dnspython.opcode',
    'dnspython.rcode',
    'dnspython.tsig',
    'dnspython.tsigkeyring',
    'dnspython.dnssec',
    'dnspython.e164',
    'dnspython.namedict',
    'dnspython.version',
    'dnspython.wire',
    'dnspython.ipv4',
    'dnspython.ipv6',
    'dnspython.immutable',
    'dnspython.enum',
    'dnspython.exception',
    'dnspython.set',
    'dnspython.transaction',
    'dnspython.xfr',
    'dnspython.asyncbackend',
    'dnspython.asyncquery',
    'dnspython.asyncresolver',
    'dnspython._asyncio_backend',
    'dnspython._trio_backend',
    'dnspython._features',
    'dnspython._asyncio_backend',
    'dnspython._trio_backend',
    'dnspython._asyncio_backend',
    'dnspython._trio_backend',
]

# ==================== 数据文件收集 ====================
# 所有非Python文件（模板、配置、证书、报告模板等）
datas = [
    # Nuclei模板目录
    ('rules/', 'rules'),
    
    # 内置Profile模板
    ('profiles/', 'profiles'),
    
    # Gadget链配置
    ('gadget_chains/', 'gadget_chains'),
    
    # 靶场配置文件
    ('ranges/', 'ranges'),
    
    # HTML/PDF报告模板
    ('templates/', 'templates'),
    
    # 证书存储目录占位符
    ('certs/', 'certs'),
    
    # 插件目录
    ('plugins/', 'plugins'),
    
    # 静态资源
    ('assets/', 'assets'),
    
    # 图标文件
    ('assets/icons/', 'assets/icons'),
    
    # 配置文件模板
    ('config/', 'config'),
    
    # 语言文件
    ('locales/', 'locales'),
    
    # 帮助文档
    ('docs/', 'docs'),
    
    # 示例文件
    ('examples/', 'examples'),
]

# ==================== 二进制文件收集 ====================
# 平台特定的动态链接库
binaries = []

# 根据平台添加特定的二进制文件
if sys.platform == 'win32':
    binaries.extend([
        # OpenSSL DLLs (Windows)
        # 注意：这些路径需要根据实际安装位置调整
        # ('path/to/libcrypto-1_1-x64.dll', '.'),
        # ('path/to/libssl-1_1-x64.dll', '.'),
    ])
elif sys.platform == 'linux':
    binaries.extend([
        # OpenSSL SOs (Linux)
        # ('path/to/libcrypto.so.1.1', '.'),
        # ('path/to/libssl.so.1.1', '.'),
    ])
elif sys.platform == 'darwin':
    binaries.extend([
        # OpenSSL dylibs (macOS)
        # ('path/to/libcrypto.1.1.dylib', '.'),
        # ('path/to/libssl.1.1.dylib', '.'),
    ])

# ==================== 排除模块 ====================
# 排除不需要的模块以减小体积
excludes = [
    # 测试框架
    'pytest',
    'unittest',
    'nose',
    'doctest',
    'test',
    'tests',
    '_pytest',
    'py.test',
    
    # 文档工具
    'sphinx',
    'docutils',
    'pydoc',
    
    # 开发工具
    'setuptools.command',
    'setuptools.tests',
    'pkg_resources.tests',
    'distutils.tests',
    
    # 未使用的GUI框架
    'tkinter',
    'wx',
    'PySide2',
    'PySide6',
    'PyGTK',
    
    # 未使用的数据库驱动
    'MySQLdb',
    'psycopg2',
    'pymssql',
    'cx_Oracle',
    
    # 其他
    'IPython',
    'jupyter',
    'notebook',
    'nbformat',
    'nbconvert',
    'traitlets',
    'ipykernel',
    'zmq',
    'tornado',
    'matplotlib',
    'seaborn',
    'plotly',
    'bokeh',
    'mayavi',
    'vtk',
    'PIL',
    'Pillow',
    'imageio',
    'cv2',
    'opencv',
    'ffmpeg',
    'moviepy',
    'pyglet',
    'pygame',
    'gym',
    'stable_baselines3',
    'ray',
    'dask',
    'distributed',
    'spark',
    'pyspark',
    'tensorflow',
    'keras',
    'torch',
    'torchvision',
    'torchaudio',
    'transformers',
    'huggingface_hub',
    'datasets',
    'accelerate',
    'diffusers',
    'onnx',
    'onnxruntime',
    'tensorrt',
    'openvino',
    'numba',
    'llvmlite',
    'cython',
    'Cython',
    'mypy',
    'flake8',
    'pylint',
    'black',
    'isort',
    'autopep8',
    'yapf',
    'coverage',
    'tox',
    'nox',
    'pre_commit',
    'commitizen',
    'bump2version',
    'twine',
    'wheel',
    'build',
    'pip',
    'pip._vendor',
    'wheel',
    'setuptools._distutils',
    'setuptools.command',
    'setuptools.config',
    'setuptools.depends',
    'setuptools.dist',
    'setuptools.extension',
    'setuptools.glob',
    'setuptools.installer',
    'setuptools.launch',
    'setuptools.monkey',
    'setuptools.msvc',
    'setuptools.namespaces',
    'setuptools.package_index',
    'setuptools.py34compat',
    'setuptools.sandbox',
    'setuptools.ssl_support',
    'setuptools.unicode_utils',
    'setuptools.version',
    'setuptools.wheel',
    'setuptools.windows_support',
]

# ==================== PyInstaller Analysis ====================
a = Analysis(
    [main_script],
    pathex=[],
    binaries=binaries,
    datas=datas,
    hiddenimports=hidden_imports,
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=excludes,
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

# ==================== PyInstaller PYZ ====================
pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

# ==================== PyInstaller EXE ====================
# Windows特定配置
if sys.platform == 'win32':
    exe = EXE(
        pyz,
        a.scripts,
        [],
        exclude_binaries=True,
        name=PROJECT_NAME,
        debug=False,
        bootloader_ignore_signals=False,
        strip=False,
        upx=True,
        console=False,  # 正式版本设为False隐藏控制台，调试时设为True
        icon='assets/icons/kunlun.ico',  # 程序图标
        uac_admin=True,  # 请求UAC管理员权限
        uac_uiaccess=False,
        version_file='assets/version.txt',  # Windows版本信息
    )
else:
    exe = EXE(
        pyz,
        a.scripts,
        [],
        exclude_binaries=True,
        name=PROJECT_NAME,
        debug=False,
        bootloader_ignore_signals=False,
        strip=False,
        upx=True,
        console=False,  # 正式版本设为False，调试时设为True
    )

# ==================== PyInstaller COLLECT ====================
coll = COLLECT(
    exe,
    a.binaries,
    a.zipfiles,
    a.datas,
    strip=False,
    upx=True,
    upx_exclude=[],
    name=PROJECT_NAME,
)
