"""
安全测试工具专家级模块系统
昆仑安全实验室 - 荣誉出品
"""

from .base import ModuleBase, ModuleStatus
from .proxy import ProxyModule
from .repeater import RepeaterModule
from .intruder import IntruderModule
from .decoder import DecoderModule
from .target import TargetModule
from .spider import SpiderModule
from .scanner import ScannerModule
from .sequencer import SequencerModule
from .comparer import ComparerModule
from .extender import ExtenderModule
from .mitm import MITMModule
from .mitm_advanced import MITMAdvancedModule
from .mitm_proxy_engine import MITMProxyEngine, MITMRequest, MITMResponse, InterceptRule, InterceptAction, RuleMatchType
from .mitm_advanced_features import TrafficProcessor, SmartTrafficMarker, TrafficReplayer, EncodingType
from .mitm_script_extension import ScriptManager, ScriptHook
from .mitm_passive_scanner import PassiveScanner, VulnFinding, VulnType
from .webfuzzer import WebFuzzerModule
from .yakrunner import YakRunnerModule
from .portscan import PortScanModule
from .poc import POCModule
from .reverseshell import ReverseShellHandler
from .codec import CodecModule
from .space_engine import SpaceEngineModule
from .pluginstore import PluginStoreModule
from .knowledge_base import KnowledgeBaseModule
from .ai_security import AISecurityDetectionModule
from .attack_orchestrator import AttackOrchestrationSystem, AttackOrchestrationModule
from .fingerprint import FingerprintRecognitionModule
from .plugin_manager import PluginManagerModule
from .asset_manager import AssetModule
from .vuln_manager import VulnerabilityModule
from .nuclei_models import (
    NucleiTemplate, NucleiVerifyResult, NucleiTemplateStats,
    NucleiSeverity, TemplateInfo, HTTPRequest, Matcher, Extractor,
    MatcherType, MatcherPart, MatcherCondition, ExtractorType,
    HTTPMethod, AttackType, TemplateClassification,
)
from .nuclei_helpers import NucleiVariableContext, NucleiHelpers, evaluate_dsl_expression
from .nuclei_executor import (
    NucleiExecutor, NucleiTemplateLoader, NucleiHTTPExecutor,
    NucleiMatcherEngine, NucleiExtractorEngine,
)
from .passive_scanner import (
    PassiveScanner as PassiveScanEngine,
    PassiveRuleLoader, PassiveRuleEngine, PassiveRule,
    PassiveScanFinding, PassiveSeverity, PassiveRuleCategory,
    PassiveScannerIntegration,
)
from .privesc_collector import PrivescCollector, PrivescCollectionResult
from .privesc_analyzer import PrivescAnalyzer, PrivescAnalysisResult, RiskFinding, RiskLevel, RiskColor
from .privesc_beacon import (
    PrivescBeaconIntegration, PrivescCommandType, PrivescTaskStatus,
    PrivescTask, get_privesc_integration,
)
from .privesc_exploit_engine import (
    PrivescExploitEngine, ExploitStrategy, ExploitStatus, EDRLevel,
    ExploitTool, ExploitStep, ExploitChain, ExploitResult,
    EXPLOIT_TOOLS, COMPOSITE_EXPLOIT_CHAINS,
)
from .privesc_report import (
    PrivescReportGenerator, PrivescReportChapter, AttackTimeline,
    AttackChainEvent, MITRETechnique, PRIVESC_MITRE_MAPPING,
    get_privesc_report_generator,
)
from .privesc_decision_tree import (
    PrivescDecisionTreeBuilder, MermaidDecisionTreeRenderer,
    PrivescStrategyManager, DecisionTree, DecisionNode, DecisionEdge,
    ExploitPath, PriorityMatrix, DecisionStrategy, NodeRole, EdgeType,
    get_decision_tree_builder, get_strategy_manager,
)
from .privesc_arsenal import (
    PrivescArsenalManager, ArsenalTool, InjectionResult,
    ArsenalStatus, InjectionMethod, ARSENAL_CATALOG,
    get_arsenal_manager,
)
from .privesc_evasion import (
    EDRDetector, AMSIETWBypass, PayloadObfuscator, EvasionPluginLoader,
    EDRInfo, EvasionResult, EDRScanResult,
    EDRVendor, EvasionTechnique, EvasionStatus,
    EDR_SIGNATURES,
    get_edr_detector, get_amsi_etw_bypass, get_payload_obfuscator, get_plugin_loader,
)
from .privesc_rl_agent import (
    PrivescRLFramework, QLearningAgent, SB3Adapter, DynamicThresholdManager,
    RewardFunction, MDPState, ExploitAction, RLTransition, LearningResult,
    PrivilegeState, RLMode,
    get_rl_framework,
)
from .privesc_graph import (
    PrivescGraphInterface, LocalGraphStore, PrivescPathAnalyzer, KnowledgeFederator,
    GraphNode, GraphEdge, AttackPath, KnowledgeEntry,
    GraphNodeType, GraphEdgeType, GraphSyncStatus,
    get_graph_interface,
)
from .privesc_audit import (
    PrivescAuditModule, AuditLogStore, AuthorizationManager, TeamCollaboration,
    ComplianceReportGenerator,
    AuditEvent, AuthorizationRequest, ComplianceReport,
    AuditEventType, AuditSeverity, AuthorizationStatus, ComplianceStandard,
    get_audit_module,
)
from .cloud_privesc import (
    CloudPrivescDetector, CloudMetadataDetector, ContainerEscapeDetector,
    K8sPrivescDetector,
    CloudMetadata, ContainerInfo, K8sInfo,
    CloudProvider, ContainerRuntime, EscapeRisk,
    CLOUD_METADATA_ENDPOINTS, CONTAINER_ESCAPE_CVES,
    get_cloud_privesc_detector,
)
from .domain_privesc import (
    DomainPrivescDetector, KerberosDelegationDetector, ADCSDetector,
    ShadowCredentialsDetector, DomainTrustDetector,
    DelegationInfo, ADCSVulnerability, ShadowCredentialInfo, TrustRelationship,
    DelegationType, ADCSEscType, TrustType,
    ADCS_ESC_TEMPLATES,
    get_domain_privesc_detector,
)
from .knowledge_base import (
    KnowledgeBaseInterface, GTFOBinsClient, LOLBASClient, WADComsClient,
    KnowledgeEntry as KBKnowledgeEntry, CacheInfo,
    KnowledgeSource, PlatformType as KBPlatformType,
    GTFOBINS_BASE_URL, GTFOBINS_API_URL,
    LOLBAS_BASE_URL, LOLBAS_API_URL,
    get_knowledge_base,
)
from .poc_research import (
    PocResearchModule, WindowsPatchAnalyzer, LinuxKernelVulnDetector,
    PocDownloader, PocCompiler, PocSandboxValidator,
    PatchInfo, KernelVuln, PocResult,
    PlatformType as PocPlatformType, PocStatus, Severity,
    MSRC_BULLETIN_DB, KNOWN_EXPLOITABLE_PATCHES, KERNEL_EXPLOIT_DB,
    get_poc_research,
)
from .privesc_stealth import (
    PrivescStealthModule, KernelProtectionDetector, NtdllHookDetector,
    SyscallBypass, FilelessExecutor, DKOMManager, DriverCleanup,
    KernelProtectionInfo, HookDetectionResult, FilelessExecutionResult,
    StealthAssessment,
    StealthLevel, HookStatus, ExecutionMode, RiskLevel,
    CRITICAL_FUNCTIONS, ORIGINAL_BYTES_DB, SYSCALL_NUMBERS,
    get_stealth_module,
)
from .privesc_self_healing import (
    PrivescSelfHealingModule, SystemStateCapturer, AutoRollback,
    FallbackChainManager, SelfHealingManager,
    SystemStateSnapshot, RollbackResult, FallbackStrategy, HealResult,
    SelfHealingReport,
    RollbackStatus, ExploitTier, HealStatus,
    FALLBACK_CHAIN_WINDOWS, FALLBACK_CHAIN_LINUX,
    get_self_healing_module,
)
from .privesc_cross_platform import (
    PrivescCrossPlatformModule, UnifiedCheckExecutor, CommandDispatcher,
    PlatformInfoCollector, CrossPlatformCredentialFinder, CrossPlatformLateralMover,
    PlatformInfo, CheckResult, CrossPlatformCredential, PrivescCheckReport,
    TargetPlatform, CheckCategory, LateralMovementMethod,
    CHECK_COMMANDS_WINDOWS, CHECK_COMMANDS_LINUX,
    get_cross_platform_module,
)
from .privesc_scheduler import (
    PrivescTaskScheduler, ScheduledPrivescChecker, PrivescWorkflowEngine,
    PrivescTask, TaskPriority, TaskStatus, TaskType,
    WorkflowTemplate, WorkflowInstance, WorkflowStep, WorkflowStepStatus,
    get_task_scheduler, get_workflow_engine,
)
from .privesc_self_test import (
    PrivescSelfTestModule, VulnerableScenarioSimulator, TestCaseLibrary,
    RuleValidator, TestExecutor,
    TestCase, TestExecutionResult, RuleMetrics, TestSuiteReport,
    TestResult, VulnScenario,
    get_self_test_module,
)
from .privesc_observability import (
    PrivescObservabilityModule, TraceCollector, ErrorAggregator,
    PerformanceBenchmark, DiagnosticDashboardProvider,
    TraceContext, Trace, Span, DiagnosticEvent, ErrorAggregation,
    PerformanceMetrics, DiagnosticDashboard,
    SpanStatus, DiagnosticLevel,
    get_observability_module,
)
from .privesc_config import (
    PrivescConfigModule, PrivescConfigManager, HotUpdateDistributor,
    ConfigStorage,
    PolicyConfig, BeaconGroup, RuleEntry, KnowledgeEntry,
    UpdateManifest, ConfigSnapshot,
    ConfigScope, ConfigKey,
    get_config_module,
)

__all__ = [
    'ModuleBase', 'ModuleStatus',
    'ProxyModule',
    'RepeaterModule',
    'IntruderModule',
    'ScannerModule',
    'SpiderModule',
    'SequencerModule',
    'DecoderModule',
    'ComparerModule',
    'TargetModule',
    'MITMModule',
    'MITMAdvancedModule',
    'MITMProxyEngine',
    'MITMRequest',
    'MITMResponse',
    'InterceptRule',
    'InterceptAction',
    'RuleMatchType',
    'TrafficProcessor',
    'SmartTrafficMarker',
    'TrafficReplayer',
    'EncodingType',
    'ScriptManager',
    'ScriptHook',
    'PassiveScanner',
    'VulnFinding',
    'VulnType',
    'WebFuzzerModule',
    'YakRunnerModule',
    'PortScanModule',
    'POCModule',
    'ReverseShellHandler',
    'CodecModule',
    'SpaceEngineModule',
    'ExtenderModule',
    'PluginStoreModule',
    'KnowledgeBaseModule',
    'AISecurityDetectionModule',
    'AttackOrchestrationSystem',
    'AttackOrchestrationModule',
    'FingerprintRecognitionModule',
    'PluginManagerModule',
    'AssetModule',
    'VulnerabilityModule',
    'NucleiTemplate',
    'NucleiVerifyResult',
    'NucleiTemplateStats',
    'NucleiSeverity',
    'TemplateInfo',
    'HTTPRequest',
    'Matcher',
    'Extractor',
    'MatcherType',
    'MatcherPart',
    'MatcherCondition',
    'ExtractorType',
    'HTTPMethod',
    'AttackType',
    'TemplateClassification',
    'NucleiVariableContext',
    'NucleiHelpers',
    'evaluate_dsl_expression',
    'NucleiExecutor',
    'NucleiTemplateLoader',
    'NucleiHTTPExecutor',
    'NucleiMatcherEngine',
    'NucleiExtractorEngine',
    'PassiveScanEngine',
    'PassiveRuleLoader',
    'PassiveRuleEngine',
    'PassiveRule',
    'PassiveScanFinding',
    'PassiveSeverity',
    'PassiveRuleCategory',
    'PassiveScannerIntegration',
    'PrivescCollector',
    'PrivescCollectionResult',
    'PrivescAnalyzer',
    'PrivescAnalysisResult',
    'RiskFinding',
    'RiskLevel',
    'RiskColor',
    'PrivescBeaconIntegration',
    'PrivescCommandType',
    'PrivescTaskStatus',
    'PrivescTask',
    'get_privesc_integration',
    'PrivescExploitEngine',
    'ExploitStrategy',
    'ExploitStatus',
    'EDRLevel',
    'ExploitTool',
    'ExploitStep',
    'ExploitChain',
    'ExploitResult',
    'EXPLOIT_TOOLS',
    'COMPOSITE_EXPLOIT_CHAINS',
    'PrivescReportGenerator',
    'PrivescReportChapter',
    'AttackTimeline',
    'AttackChainEvent',
    'MITRETechnique',
    'PRIVESC_MITRE_MAPPING',
    'get_privesc_report_generator',
    'PrivescDecisionTreeBuilder',
    'MermaidDecisionTreeRenderer',
    'PrivescStrategyManager',
    'DecisionTree',
    'DecisionNode',
    'DecisionEdge',
    'ExploitPath',
    'PriorityMatrix',
    'DecisionStrategy',
    'NodeRole',
    'EdgeType',
    'get_decision_tree_builder',
    'get_strategy_manager',
    'PrivescArsenalManager',
    'ArsenalTool',
    'InjectionResult',
    'ArsenalStatus',
    'InjectionMethod',
    'ARSENAL_CATALOG',
    'get_arsenal_manager',
    'EDRDetector',
    'AMSIETWBypass',
    'PayloadObfuscator',
    'EvasionPluginLoader',
    'EDRInfo',
    'EvasionResult',
    'EDRScanResult',
    'EDRVendor',
    'EvasionTechnique',
    'EvasionStatus',
    'EDR_SIGNATURES',
    'get_edr_detector',
    'get_amsi_etw_bypass',
    'get_payload_obfuscator',
    'get_plugin_loader',
    'PrivescRLFramework',
    'QLearningAgent',
    'SB3Adapter',
    'DynamicThresholdManager',
    'RewardFunction',
    'MDPState',
    'ExploitAction',
    'RLTransition',
    'LearningResult',
    'PrivilegeState',
    'RLMode',
    'get_rl_framework',
    'PrivescGraphInterface',
    'LocalGraphStore',
    'PrivescPathAnalyzer',
    'KnowledgeFederator',
    'GraphNode',
    'GraphEdge',
    'AttackPath',
    'KnowledgeEntry',
    'GraphNodeType',
    'GraphEdgeType',
    'GraphSyncStatus',
    'get_graph_interface',
    'PrivescAuditModule',
    'AuditLogStore',
    'AuthorizationManager',
    'TeamCollaboration',
    'ComplianceReportGenerator',
    'AuditEvent',
    'AuthorizationRequest',
    'ComplianceReport',
    'AuditEventType',
    'AuditSeverity',
    'AuthorizationStatus',
    'ComplianceStandard',
    'get_audit_module',
    'CloudPrivescDetector',
    'CloudMetadataDetector',
    'ContainerEscapeDetector',
    'K8sPrivescDetector',
    'CloudMetadata',
    'ContainerInfo',
    'K8sInfo',
    'CloudProvider',
    'ContainerRuntime',
    'EscapeRisk',
    'CLOUD_METADATA_ENDPOINTS',
    'CONTAINER_ESCAPE_CVES',
    'get_cloud_privesc_detector',
    'DomainPrivescDetector',
    'KerberosDelegationDetector',
    'ADCSDetector',
    'ShadowCredentialsDetector',
    'DomainTrustDetector',
    'DelegationInfo',
    'ADCSVulnerability',
    'ShadowCredentialInfo',
    'TrustRelationship',
    'DelegationType',
    'ADCSEscType',
    'TrustType',
    'ADCS_ESC_TEMPLATES',
    'get_domain_privesc_detector',
    'KnowledgeBaseInterface',
    'GTFOBinsClient',
    'LOLBASClient',
    'WADComsClient',
    'KBKnowledgeEntry',
    'CacheInfo',
    'KnowledgeSource',
    'KBPlatformType',
    'GTFOBINS_BASE_URL',
    'GTFOBINS_API_URL',
    'LOLBAS_BASE_URL',
    'LOLBAS_API_URL',
    'get_knowledge_base',
    'PocResearchModule',
    'WindowsPatchAnalyzer',
    'LinuxKernelVulnDetector',
    'PocDownloader',
    'PocCompiler',
    'PocSandboxValidator',
    'PatchInfo',
    'KernelVuln',
    'PocResult',
    'PocPlatformType',
    'PocStatus',
    'Severity',
    'MSRC_BULLETIN_DB',
    'KNOWN_EXPLOITABLE_PATCHES',
    'KERNEL_EXPLOIT_DB',
    'get_poc_research',
    'PrivescStealthModule',
    'KernelProtectionDetector',
    'NtdllHookDetector',
    'SyscallBypass',
    'FilelessExecutor',
    'DKOMManager',
    'DriverCleanup',
    'KernelProtectionInfo',
    'HookDetectionResult',
    'FilelessExecutionResult',
    'StealthAssessment',
    'StealthLevel',
    'HookStatus',
    'ExecutionMode',
    'RiskLevel',
    'CRITICAL_FUNCTIONS',
    'ORIGINAL_BYTES_DB',
    'SYSCALL_NUMBERS',
    'get_stealth_module',
    'PrivescSelfHealingModule',
    'SystemStateCapturer',
    'AutoRollback',
    'FallbackChainManager',
    'SelfHealingManager',
    'SystemStateSnapshot',
    'RollbackResult',
    'FallbackStrategy',
    'HealResult',
    'SelfHealingReport',
    'RollbackStatus',
    'ExploitTier',
    'HealStatus',
    'FALLBACK_CHAIN_WINDOWS',
    'FALLBACK_CHAIN_LINUX',
    'get_self_healing_module',
    'PrivescCrossPlatformModule',
    'UnifiedCheckExecutor',
    'CommandDispatcher',
    'PlatformInfoCollector',
    'CrossPlatformCredentialFinder',
    'CrossPlatformLateralMover',
    'PlatformInfo',
    'CheckResult',
    'CrossPlatformCredential',
    'PrivescCheckReport',
    'TargetPlatform',
    'CheckCategory',
    'LateralMovementMethod',
    'CHECK_COMMANDS_WINDOWS',
    'CHECK_COMMANDS_LINUX',
    'get_cross_platform_module',
    'PrivescTaskScheduler',
    'ScheduledPrivescChecker',
    'PrivescWorkflowEngine',
    'TaskPriority',
    'TaskStatus',
    'TaskType',
    'WorkflowTemplate',
    'WorkflowInstance',
    'WorkflowStep',
    'WorkflowStepStatus',
    'get_task_scheduler',
    'get_workflow_engine',
    'PrivescSelfTestModule',
    'VulnerableScenarioSimulator',
    'TestCaseLibrary',
    'RuleValidator',
    'TestExecutor',
    'TestResult',
    'VulnScenario',
    'get_self_test_module',
    'PrivescObservabilityModule',
    'TraceCollector',
    'ErrorAggregator',
    'PerformanceBenchmark',
    'DiagnosticDashboardProvider',
    'TraceContext',
    'Trace',
    'Span',
    'DiagnosticEvent',
    'ErrorAggregation',
    'PerformanceMetrics',
    'DiagnosticDashboard',
    'SpanStatus',
    'DiagnosticLevel',
    'get_observability_module',
    'PrivescConfigModule',
    'PrivescConfigManager',
    'HotUpdateDistributor',
    'ConfigStorage',
    'PolicyConfig',
    'BeaconGroup',
    'RuleEntry',
    'KnowledgeEntry',
    'UpdateManifest',
    'ConfigSnapshot',
    'ConfigScope',
    'ConfigKey',
    'get_config_module',
]
