"""Built-in ATT&CK technique database for Kunlun penetration testing platform."""

from typing import Dict

from .attck_mapper import AttckTactic, AttckTechnique, Severity


BUILTIN_TECHNIQUES: Dict[str, AttckTechnique] = {
    "T1190": AttckTechnique(
        technique_id="T1190",
        name="Exploit Public-Facing Application",
        tactic=AttckTactic.INITIAL_ACCESS,
        description="利用面向公共应用程序的漏洞获取初始访问权限。",
        severity=Severity.CRITICAL,
        detection_suggestions=["监控Web应用程序漏洞利用尝试", "部署WAF规则检测已知漏洞利用模式", "保持应用程序和依赖项最新"],
        mitigation_suggestions=["及时应用安全补丁", "实施Web应用程序防火墙", "定期进行漏洞扫描和渗透测试"],
        platforms=["Windows", "Linux", "macOS", "Network"],
        data_sources=["Web Application Firewall Logs", "Network Traffic", "Application Logs"],
    ),
    "T1078": AttckTechnique(
        technique_id="T1078",
        name="Valid Accounts",
        tactic=AttckTactic.INITIAL_ACCESS,
        description="使用有效账户凭据获取系统访问权限。",
        severity=Severity.HIGH,
        detection_suggestions=["监控异常登录行为", "实施多因素认证", "定期审查账户权限"],
        mitigation_suggestions=["启用MFA", "实施最小权限原则", "定期轮换凭据"],
        platforms=["Windows", "Linux", "macOS", "Office 365", "Azure AD", "Google Workspace"],
        data_sources=["Authentication Logs", "Account Usage", "Active Directory"],
    ),
    "T1133": AttckTechnique(
        technique_id="T1133",
        name="External Remote Services",
        tactic=AttckTactic.INITIAL_ACCESS,
        description="通过外部远程服务（如VPN、RDP）获取初始访问。",
        severity=Severity.HIGH,
        detection_suggestions=["监控VPN和远程桌面登录", "检测异常地理位置登录", "审计远程服务配置"],
        mitigation_suggestions=["限制远程服务暴露面", "实施网络分段", "使用强认证机制"],
        platforms=["Windows", "Linux", "macOS"],
        data_sources=["VPN Logs", "RDP Logs", "Network Traffic"],
    ),
    "T1059": AttckTechnique(
        technique_id="T1059",
        name="Command and Scripting Interpreter",
        tactic=AttckTactic.EXECUTION,
        description="通过命令和脚本解释器执行恶意代码。",
        severity=Severity.HIGH,
        detection_suggestions=["监控PowerShell执行日志", "检测异常脚本执行", "启用脚本块日志记录"],
        mitigation_suggestions=["限制脚本执行权限", "实施应用程序白名单", "启用PowerShell约束语言模式"],
        platforms=["Windows", "Linux", "macOS"],
        data_sources=["Process Creation", "PowerShell Logs", "Script Block Logging"],
        sub_techniques=["T1059.001", "T1059.003", "T1059.004", "T1059.005"],
    ),
    "T1059.001": AttckTechnique(
        technique_id="T1059.001",
        name="PowerShell",
        tactic=AttckTactic.EXECUTION,
        description="使用PowerShell执行恶意命令和脚本。",
        severity=Severity.HIGH,
        detection_suggestions=["启用PowerShell模块日志", "监控可疑PowerShell命令", "检测编码的PowerShell执行"],
        mitigation_suggestions=["限制PowerShell执行策略", "启用约束语言模式", "部署AMSI集成"],
        platforms=["Windows"],
        data_sources=["PowerShell Logs", "Process Creation", "Script Block Logging"],
    ),
    "T1059.003": AttckTechnique(
        technique_id="T1059.003",
        name="Windows Command Shell",
        tactic=AttckTactic.EXECUTION,
        description="使用Windows命令解释器(cmd.exe)执行命令。",
        severity=Severity.MEDIUM,
        detection_suggestions=["监控cmd.exe执行", "检测可疑命令行参数", "记录命令历史记录"],
        mitigation_suggestions=["限制cmd.exe访问", "实施应用程序控制", "启用命令日志记录"],
        platforms=["Windows"],
        data_sources=["Process Creation", "Command Line Arguments"],
    ),
    "T1059.004": AttckTechnique(
        technique_id="T1059.004",
        name="Unix Shell",
        tactic=AttckTactic.EXECUTION,
        description="使用Unix/Linux shell执行命令。",
        severity=Severity.MEDIUM,
        detection_suggestions=["监控shell执行历史", "检测异常命令序列", "启用审计日志"],
        mitigation_suggestions=["限制shell访问权限", "实施命令审计", "使用受限shell环境"],
        platforms=["Linux", "macOS"],
        data_sources=["Shell History", "Process Creation", "Audit Logs"],
    ),
    "T1059.005": AttckTechnique(
        technique_id="T1059.005",
        name="Visual Basic",
        tactic=AttckTactic.EXECUTION,
        description="使用Visual Basic和VBScript执行代码。",
        severity=Severity.MEDIUM,
        detection_suggestions=["监控VBS脚本执行", "检测Office宏执行", "启用脚本日志"],
        mitigation_suggestions=["禁用Office宏", "限制WScript/cscript执行", "实施应用程序白名单"],
        platforms=["Windows"],
        data_sources=["Process Creation", "Office Logs", "Script Execution"],
    ),
    "T1203": AttckTechnique(
        technique_id="T1203",
        name="Exploitation for Client Execution",
        tactic=AttckTactic.EXECUTION,
        description="利用客户端应用程序漏洞执行代码。",
        severity=Severity.CRITICAL,
        detection_suggestions=["监控客户端漏洞利用尝试", "检测异常进程启动", "启用应用程序日志"],
        mitigation_suggestions=["保持客户端应用程序最新", "实施应用程序沙箱", "部署端点保护"],
        platforms=["Windows", "Linux", "macOS"],
        data_sources=["Process Creation", "Application Logs", "Endpoint Detection"],
    ),
    "T1047": AttckTechnique(
        technique_id="T1047",
        name="Windows Management Instrumentation",
        tactic=AttckTactic.EXECUTION,
        description="使用WMI执行命令和脚本。",
        severity=Severity.HIGH,
        detection_suggestions=["监控WMI事件订阅", "检测异常WMI查询", "启用WMI活动日志"],
        mitigation_suggestions=["限制WMI访问权限", "监控WMI进程创建", "实施网络分段"],
        platforms=["Windows"],
        data_sources=["WMI Activity", "Process Creation", "Network Traffic"],
    ),
    "T1053": AttckTechnique(
        technique_id="T1053",
        name="Scheduled Task/Job",
        tactic=AttckTactic.PERSISTENCE,
        description="使用计划任务实现持久化。",
        severity=Severity.HIGH,
        detection_suggestions=["监控计划任务创建", "检测异常任务计划", "审计任务执行历史"],
        mitigation_suggestions=["限制计划任务创建权限", "定期审计计划任务", "实施最小权限原则"],
        platforms=["Windows", "Linux"],
        data_sources=["Scheduled Task Logs", "Process Creation", "File Creation"],
        sub_techniques=["T1053.005"],
    ),
    "T1053.005": AttckTechnique(
        technique_id="T1053.005",
        name="Scheduled Task",
        tactic=AttckTactic.PERSISTENCE,
        description="使用Windows计划任务实现持久化。",
        severity=Severity.HIGH,
        detection_suggestions=["监控schtasks.exe执行", "检测新计划任务创建", "审计任务触发器"],
        mitigation_suggestions=["限制计划任务权限", "启用任务审计", "实施应用程序控制"],
        platforms=["Windows"],
        data_sources=["Scheduled Task Logs", "Process Creation", "Registry Modification"],
    ),
    "T1547": AttckTechnique(
        technique_id="T1547",
        name="Boot or Logon Autostart Execution",
        tactic=AttckTactic.PERSISTENCE,
        description="通过启动项实现开机自启动持久化。",
        severity=Severity.HIGH,
        detection_suggestions=["监控启动项修改", "检测新注册表Run键", "审计启动文件夹变更"],
        mitigation_suggestions=["限制启动项修改权限", "定期审查启动项", "实施应用程序白名单"],
        platforms=["Windows", "Linux", "macOS"],
        data_sources=["Registry Modification", "File Creation", "Process Creation"],
        sub_techniques=["T1547.001", "T1547.004"],
    ),
    "T1547.001": AttckTechnique(
        technique_id="T1547.001",
        name="Registry Run Keys / Startup Folder",
        tactic=AttckTactic.PERSISTENCE,
        description="通过注册表Run键或启动文件夹实现持久化。",
        severity=Severity.HIGH,
        detection_suggestions=["监控注册表Run键修改", "检测启动文件夹新文件", "启用注册表审计"],
        mitigation_suggestions=["限制注册表写入权限", "定期审查启动项", "实施组策略控制"],
        platforms=["Windows"],
        data_sources=["Registry Modification", "File Creation"],
    ),
    "T1543": AttckTechnique(
        technique_id="T1543",
        name="Create or Modify System Process",
        tactic=AttckTactic.PERSISTENCE,
        description="通过创建或修改系统服务实现持久化。",
        severity=Severity.HIGH,
        detection_suggestions=["监控新服务创建", "检测服务配置修改", "审计服务执行历史"],
        mitigation_suggestions=["限制服务创建权限", "定期审计系统服务", "实施服务白名单"],
        platforms=["Windows", "Linux"],
        data_sources=["Service Creation", "Registry Modification", "Process Creation"],
        sub_techniques=["T1543.003"],
    ),
    "T1543.003": AttckTechnique(
        technique_id="T1543.003",
        name="Windows Service",
        tactic=AttckTactic.PERSISTENCE,
        description="通过创建Windows服务实现持久化。",
        severity=Severity.HIGH,
        detection_suggestions=["监控sc.exe执行", "检测新服务注册", "审计服务启动类型"],
        mitigation_suggestions=["限制服务创建权限", "启用服务审计", "实施最小权限原则"],
        platforms=["Windows"],
        data_sources=["Service Creation", "Process Creation", "Registry Modification"],
    ),
    "T1068": AttckTechnique(
        technique_id="T1068",
        name="Exploitation for Privilege Escalation",
        tactic=AttckTactic.PRIVILEGE_ESCALATION,
        description="利用漏洞提升权限。",
        severity=Severity.CRITICAL,
        detection_suggestions=["监控已知漏洞利用", "检测异常权限提升", "启用内核审计"],
        mitigation_suggestions=["及时应用安全补丁", "实施最小权限原则", "部署端点保护"],
        platforms=["Windows", "Linux", "macOS"],
        data_sources=["Process Creation", "Kernel Logs", "Vulnerability Scanner"],
    ),
    "T1134": AttckTechnique(
        technique_id="T1134",
        name="Access Token Manipulation",
        tactic=AttckTactic.PRIVILEGE_ESCALATION,
        description="通过操控访问令牌提升权限。",
        severity=Severity.HIGH,
        detection_suggestions=["监控令牌模拟事件", "检测异常令牌操作", "启用安全审计日志"],
        mitigation_suggestions=["限制令牌模拟权限", "启用详细审计日志", "实施最小权限原则"],
        platforms=["Windows"],
        data_sources=["Token Manipulation", "Process Creation", "Security Logs"],
        sub_techniques=["T1134.001", "T1134.002", "T1134.003"],
    ),
    "T1134.001": AttckTechnique(
        technique_id="T1134.001",
        name="Token Impersonation/Theft",
        tactic=AttckTactic.PRIVILEGE_ESCALATION,
        description="通过窃取或模拟令牌获取更高权限。",
        severity=Severity.HIGH,
        detection_suggestions=["监控ImpersonateLoggedOnUser调用", "检测异常令牌使用", "启用进程审计"],
        mitigation_suggestions=["限制令牌模拟权限", "启用详细审计", "实施最小权限"],
        platforms=["Windows"],
        data_sources=["Token Manipulation", "API Calls", "Process Creation"],
    ),
    "T1134.002": AttckTechnique(
        technique_id="T1134.002",
        name="Create Process with Token",
        tactic=AttckTactic.PRIVILEGE_ESCALATION,
        description="使用替代令牌创建进程。",
        severity=Severity.HIGH,
        detection_suggestions=["监控CreateProcessWithTokenW调用", "检测异常进程创建", "审计令牌使用"],
        mitigation_suggestions=["限制令牌使用权限", "启用进程审计", "实施最小权限"],
        platforms=["Windows"],
        data_sources=["Process Creation", "Token Manipulation", "API Calls"],
    ),
    "T1134.003": AttckTechnique(
        technique_id="T1134.003",
        name="Make and Impersonate Token",
        tactic=AttckTactic.PRIVILEGE_ESCALATION,
        description="创建并模拟新令牌。",
        severity=Severity.HIGH,
        detection_suggestions=["监控CreateRestrictedToken调用", "检测令牌创建事件", "审计令牌模拟"],
        mitigation_suggestions=["限制令牌创建权限", "启用详细审计", "实施最小权限"],
        platforms=["Windows"],
        data_sources=["Token Creation", "API Calls", "Security Logs"],
    ),
    "T1548": AttckTechnique(
        technique_id="T1548",
        name="Abuse Elevation Control Mechanism",
        tactic=AttckTactic.PRIVILEGE_ESCALATION,
        description="滥用权限提升控制机制（如UAC绕过）。",
        severity=Severity.HIGH,
        detection_suggestions=["监控UAC绕过技术", "检测异常提权行为", "启用UAC日志"],
        mitigation_suggestions=["配置UAC为最高级别", "限制管理员权限", "实施应用程序控制"],
        platforms=["Windows"],
        data_sources=["UAC Logs", "Process Creation", "Registry Modification"],
        sub_techniques=["T1548.002"],
    ),
    "T1548.002": AttckTechnique(
        technique_id="T1548.002",
        name="Bypass User Account Control",
        tactic=AttckTactic.PRIVILEGE_ESCALATION,
        description="绕过用户账户控制(UAC)获取管理员权限。",
        severity=Severity.HIGH,
        detection_suggestions=["监控已知UAC绕过技术", "检测异常COM对象使用", "启用UAC详细日志"],
        mitigation_suggestions=["设置UAC为AlwaysNotify", "限制COM对象访问", "实施应用程序白名单"],
        platforms=["Windows"],
        data_sources=["UAC Logs", "COM Activity", "Process Creation"],
    ),
    "T1027": AttckTechnique(
        technique_id="T1027",
        name="Obfuscated Files or Information",
        tactic=AttckTactic.DEFENSE_EVASION,
        description="使用混淆技术隐藏恶意代码或信息。",
        severity=Severity.MEDIUM,
        detection_suggestions=["检测混淆的脚本文件", "监控编码的可执行文件", "启用AMSI扫描"],
        mitigation_suggestions=["部署AMSI集成", "启用脚本日志", "实施应用程序控制"],
        platforms=["Windows", "Linux", "macOS"],
        data_sources=["File Creation", "Process Creation", "Script Execution"],
        sub_techniques=["T1027.001", "T1027.002"],
    ),
    "T1027.001": AttckTechnique(
        technique_id="T1027.001",
        name="Binary Padding",
        tactic=AttckTactic.DEFENSE_EVASION,
        description="使用二进制填充改变文件大小以规避检测。",
        severity=Severity.MEDIUM,
        detection_suggestions=["检测异常文件大小", "监控文件哈希变化", "启用文件审计"],
        mitigation_suggestions=["实施文件完整性监控", "部署端点保护", "启用文件审计"],
        platforms=["Windows", "Linux", "macOS"],
        data_sources=["File Creation", "File Modification"],
    ),
    "T1027.002": AttckTechnique(
        technique_id="T1027.002",
        name="Software Packing",
        tactic=AttckTactic.DEFENSE_EVASION,
        description="使用软件打包工具压缩和混淆可执行文件。",
        severity=Severity.MEDIUM,
        detection_suggestions=["检测打包的可执行文件", "监控已知打包工具", "启用静态分析"],
        mitigation_suggestions=["部署静态分析工具", "实施应用程序白名单", "启用文件审计"],
        platforms=["Windows", "Linux", "macOS"],
        data_sources=["File Creation", "Static Analysis", "Process Creation"],
    ),
    "T1055": AttckTechnique(
        technique_id="T1055",
        name="Process Injection",
        tactic=AttckTactic.DEFENSE_EVASION,
        description="将代码注入到另一个进程执行。",
        severity=Severity.CRITICAL,
        detection_suggestions=["监控进程注入API调用", "检测异常内存操作", "启用ETW日志"],
        mitigation_suggestions=["部署端点保护", "启用ETW日志", "实施应用程序控制"],
        platforms=["Windows", "Linux", "macOS"],
        data_sources=["Process Access", "API Calls", "ETW Logs"],
        sub_techniques=["T1055.001", "T1055.012"],
    ),
    "T1055.001": AttckTechnique(
        technique_id="T1055.001",
        name="Dynamic-link Library Injection",
        tactic=AttckTactic.DEFENSE_EVASION,
        description="通过DLL注入将代码注入到进程。",
        severity=Severity.CRITICAL,
        detection_suggestions=["监控DLL加载事件", "检测异常DLL路径", "启用进程审计"],
        mitigation_suggestions=["实施DLL白名单", "启用进程审计", "部署端点保护"],
        platforms=["Windows"],
        data_sources=["DLL Load", "Process Access", "Registry Modification"],
    ),
    "T1055.012": AttckTechnique(
        technique_id="T1055.012",
        name="Process Hollowing",
        tactic=AttckTactic.DEFENSE_EVASION,
        description="通过进程空洞化技术注入代码。",
        severity=Severity.CRITICAL,
        detection_suggestions=["监控NtUnmapViewOfSection调用", "检测异常进程内存修改", "启用ETW日志"],
        mitigation_suggestions=["部署端点保护", "启用ETW日志", "实施应用程序控制"],
        platforms=["Windows"],
        data_sources=["Process Access", "API Calls", "ETW Logs"],
    ),
    "T1562": AttckTechnique(
        technique_id="T1562",
        name="Impair Defenses",
        tactic=AttckTactic.DEFENSE_EVASION,
        description="削弱或禁用防御机制。",
        severity=Severity.HIGH,
        detection_suggestions=["监控安全软件禁用事件", "检测日志清除行为", "启用安全审计"],
        mitigation_suggestions=["限制安全软件配置权限", "启用日志保护", "实施最小权限原则"],
        platforms=["Windows", "Linux", "macOS"],
        data_sources=["Security Software Logs", "Process Creation", "Registry Modification"],
        sub_techniques=["T1562.001", "T1562.004"],
    ),
    "T1562.001": AttckTechnique(
        technique_id="T1562.001",
        name="Disable or Modify Tools",
        tactic=AttckTactic.DEFENSE_EVASION,
        description="禁用或修改安全工具。",
        severity=Severity.HIGH,
        detection_suggestions=["监控安全服务停止", "检测安全软件配置修改", "启用服务审计"],
        mitigation_suggestions=["限制安全服务配置权限", "启用服务审计", "实施最小权限"],
        platforms=["Windows", "Linux", "macOS"],
        data_sources=["Security Software Logs", "Service Modification", "Process Creation"],
    ),
    "T1562.004": AttckTechnique(
        technique_id="T1562.004",
        name="Disable or Modify System Firewall",
        tactic=AttckTactic.DEFENSE_EVASION,
        description="禁用或修改系统防火墙。",
        severity=Severity.HIGH,
        detection_suggestions=["监控防火墙配置修改", "检测防火墙规则变更", "启用防火墙审计"],
        mitigation_suggestions=["限制防火墙配置权限", "启用防火墙审计", "实施网络分段"],
        platforms=["Windows", "Linux", "macOS"],
        data_sources=["Firewall Logs", "Registry Modification", "Process Creation"],
    ),
    "T1003": AttckTechnique(
        technique_id="T1003",
        name="OS Credential Dumping",
        tactic=AttckTactic.CREDENTIAL_ACCESS,
        description="导出操作系统凭据。",
        severity=Severity.CRITICAL,
        detection_suggestions=["监控LSASS内存访问", "检测凭据转储工具", "启用安全审计日志"],
        mitigation_suggestions=["启用Credential Guard", "限制LSASS访问权限", "实施最小权限原则"],
        platforms=["Windows", "Linux", "macOS"],
        data_sources=["Process Access", "Security Logs", "Endpoint Detection"],
        sub_techniques=["T1003.001", "T1003.002", "T1003.003"],
    ),
    "T1003.001": AttckTechnique(
        technique_id="T1003.001",
        name="LSASS Memory",
        tactic=AttckTactic.CREDENTIAL_ACCESS,
        description="从LSASS进程内存中提取凭据。",
        severity=Severity.CRITICAL,
        detection_suggestions=["监控LSASS内存读取", "检测Mimikatz等工具", "启用Credential Guard"],
        mitigation_suggestions=["启用Credential Guard", "限制LSASS访问", "部署端点保护"],
        platforms=["Windows"],
        data_sources=["Process Access", "Security Logs", "Endpoint Detection"],
    ),
    "T1003.002": AttckTechnique(
        technique_id="T1003.002",
        name="Security Account Manager",
        tactic=AttckTactic.CREDENTIAL_ACCESS,
        description="从SAM数据库提取凭据。",
        severity=Severity.CRITICAL,
        detection_suggestions=["监控SAM文件访问", "检测注册表SAM导出", "启用安全审计"],
        mitigation_suggestions=["限制SAM访问权限", "启用安全审计", "实施最小权限"],
        platforms=["Windows"],
        data_sources=["Registry Access", "File Access", "Security Logs"],
    ),
    "T1003.003": AttckTechnique(
        technique_id="T1003.003",
        name="NTDS",
        tactic=AttckTactic.CREDENTIAL_ACCESS,
        description="从NTDS.dit提取Active Directory凭据。",
        severity=Severity.CRITICAL,
        detection_suggestions=["监控NTDS.dit文件访问", "检测卷影复制创建", "启用域控制器审计"],
        mitigation_suggestions=["限制域控制器访问", "启用详细审计", "实施最小权限"],
        platforms=["Windows"],
        data_sources=["File Access", "Volume Shadow Copy", "Security Logs"],
    ),
    "T1552": AttckTechnique(
        technique_id="T1552",
        name="Unsecured Credentials",
        tactic=AttckTactic.CREDENTIAL_ACCESS,
        description="从不安全的凭据存储中获取凭据。",
        severity=Severity.HIGH,
        detection_suggestions=["监控配置文件访问", "检测凭据文件搜索", "启用文件审计"],
        mitigation_suggestions=["安全存储凭据", "启用文件审计", "实施最小权限"],
        platforms=["Windows", "Linux", "macOS"],
        data_sources=["File Access", "Process Creation", "Registry Access"],
        sub_techniques=["T1552.001", "T1552.004"],
    ),
    "T1552.001": AttckTechnique(
        technique_id="T1552.001",
        name="Credentials In Files",
        tactic=AttckTactic.CREDENTIAL_ACCESS,
        description="从文件中获取凭据。",
        severity=Severity.HIGH,
        detection_suggestions=["监控敏感文件访问", "检测凭据文件搜索", "启用文件审计"],
        mitigation_suggestions=["安全存储凭据", "启用文件审计", "实施最小权限"],
        platforms=["Windows", "Linux", "macOS"],
        data_sources=["File Access", "Process Creation"],
    ),
    "T1552.004": AttckTechnique(
        technique_id="T1552.004",
        name="Private Keys",
        tactic=AttckTactic.CREDENTIAL_ACCESS,
        description="获取私钥文件。",
        severity=Severity.HIGH,
        detection_suggestions=["监控私钥文件访问", "检测证书导出", "启用文件审计"],
        mitigation_suggestions=["保护私钥存储", "启用文件审计", "实施最小权限"],
        platforms=["Windows", "Linux", "macOS"],
        data_sources=["File Access", "Certificate Logs"],
    ),
    "T1558": AttckTechnique(
        technique_id="T1558",
        name="Steal or Forge Kerberos Tickets",
        tactic=AttckTactic.CREDENTIAL_ACCESS,
        description="窃取或伪造Kerberos票据。",
        severity=Severity.CRITICAL,
        detection_suggestions=["监控Kerberos票据请求", "检测异常票据使用", "启用Kerberos审计"],
        mitigation_suggestions=["限制票据请求权限", "启用Kerberos审计", "实施最小权限"],
        platforms=["Windows"],
        data_sources=["Kerberos Logs", "Security Logs", "Network Traffic"],
        sub_techniques=["T1558.001", "T1558.003"],
    ),
    "T1558.001": AttckTechnique(
        technique_id="T1558.001",
        name="Golden Ticket",
        tactic=AttckTactic.CREDENTIAL_ACCESS,
        description="伪造黄金票据获取域管理员权限。",
        severity=Severity.CRITICAL,
        detection_suggestions=["监控异常TGT请求", "检测票据签名异常", "启用Kerberos审计"],
        mitigation_suggestions=["保护KRBTGT账户", "定期轮换KRBTGT密码", "启用Kerberos审计"],
        platforms=["Windows"],
        data_sources=["Kerberos Logs", "Security Logs"],
    ),
    "T1558.003": AttckTechnique(
        technique_id="T1558.003",
        name="Kerberoasting",
        tactic=AttckTactic.CREDENTIAL_ACCESS,
        description="通过Kerberoasting攻击获取服务账户凭据。",
        severity=Severity.HIGH,
        detection_suggestions=["监控异常TGS请求", "检测大量票据请求", "启用Kerberos审计"],
        mitigation_suggestions=["使用强服务账户密码", "限制服务账户权限", "启用Kerberos审计"],
        platforms=["Windows"],
        data_sources=["Kerberos Logs", "Security Logs", "Network Traffic"],
    ),
    "T1046": AttckTechnique(
        technique_id="T1046",
        name="Network Service Discovery",
        tactic=AttckTactic.DISCOVERY,
        description="扫描网络服务发现目标。",
        severity=Severity.MEDIUM,
        detection_suggestions=["监控端口扫描行为", "检测网络扫描工具", "启用网络流量分析"],
        mitigation_suggestions=["实施网络分段", "部署IDS/IPS", "限制网络访问"],
        platforms=["Windows", "Linux", "macOS", "Network"],
        data_sources=["Network Traffic", "Firewall Logs", "IDS/IPS Logs"],
    ),
    "T1082": AttckTechnique(
        technique_id="T1082",
        name="System Information Discovery",
        tactic=AttckTactic.DISCOVERY,
        description="收集系统信息。",
        severity=Severity.MEDIUM,
        detection_suggestions=["监控系统信息命令", "检测异常信息收集", "启用进程审计"],
        mitigation_suggestions=["限制系统信息访问", "启用进程审计", "实施最小权限"],
        platforms=["Windows", "Linux", "macOS"],
        data_sources=["Process Creation", "Command Line Arguments"],
    ),
    "T1087": AttckTechnique(
        technique_id="T1087",
        name="Account Discovery",
        tactic=AttckTactic.DISCOVERY,
        description="发现系统或域账户。",
        severity=Severity.MEDIUM,
        detection_suggestions=["监控账户枚举命令", "检测异常账户查询", "启用安全审计"],
        mitigation_suggestions=["限制账户枚举权限", "启用安全审计", "实施最小权限"],
        platforms=["Windows", "Linux", "macOS"],
        data_sources=["Process Creation", "Security Logs", "Command Line Arguments"],
        sub_techniques=["T1087.001", "T1087.002"],
    ),
    "T1087.001": AttckTechnique(
        technique_id="T1087.001",
        name="Local Account",
        tactic=AttckTactic.DISCOVERY,
        description="发现本地账户。",
        severity=Severity.MEDIUM,
        detection_suggestions=["监控net user命令", "检测本地账户查询", "启用安全审计"],
        mitigation_suggestions=["限制本地账户查询", "启用安全审计", "实施最小权限"],
        platforms=["Windows", "Linux", "macOS"],
        data_sources=["Process Creation", "Command Line Arguments"],
    ),
    "T1087.002": AttckTechnique(
        technique_id="T1087.002",
        name="Domain Account",
        tactic=AttckTactic.DISCOVERY,
        description="发现域账户。",
        severity=Severity.MEDIUM,
        detection_suggestions=["监控域账户枚举", "检测AD查询", "启用域控制器审计"],
        mitigation_suggestions=["限制域账户查询", "启用域控制器审计", "实施最小权限"],
        platforms=["Windows"],
        data_sources=["Active Directory Logs", "Security Logs", "Process Creation"],
    ),
    "T1021": AttckTechnique(
        technique_id="T1021",
        name="Remote Services",
        tactic=AttckTactic.LATERAL_MOVEMENT,
        description="使用远程服务进行横向移动。",
        severity=Severity.HIGH,
        detection_suggestions=["监控远程服务连接", "检测异常RDP/SMB连接", "启用网络流量分析"],
        mitigation_suggestions=["实施网络分段", "限制远程服务访问", "启用多因素认证"],
        platforms=["Windows", "Linux", "macOS"],
        data_sources=["Network Traffic", "Authentication Logs", "Process Creation"],
        sub_techniques=["T1021.001", "T1021.002", "T1021.004", "T1021.006"],
    ),
    "T1021.001": AttckTechnique(
        technique_id="T1021.001",
        name="Remote Desktop Protocol",
        tactic=AttckTactic.LATERAL_MOVEMENT,
        description="使用RDP进行横向移动。",
        severity=Severity.HIGH,
        detection_suggestions=["监控RDP连接", "检测异常RDP登录", "启用RDP日志"],
        mitigation_suggestions=["限制RDP访问", "启用网络级认证", "实施多因素认证"],
        platforms=["Windows"],
        data_sources=["RDP Logs", "Authentication Logs", "Network Traffic"],
    ),
    "T1021.002": AttckTechnique(
        technique_id="T1021.002",
        name="SMB/Windows Admin Shares",
        tactic=AttckTactic.LATERAL_MOVEMENT,
        description="使用SMB和管理共享进行横向移动。",
        severity=Severity.HIGH,
        detection_suggestions=["监控SMB连接", "检测管理共享访问", "启用SMB审计"],
        mitigation_suggestions=["限制管理共享访问", "启用SMB审计", "实施网络分段"],
        platforms=["Windows"],
        data_sources=["SMB Logs", "File Access", "Process Creation"],
    ),
    "T1021.004": AttckTechnique(
        technique_id="T1021.004",
        name="SSH",
        tactic=AttckTactic.LATERAL_MOVEMENT,
        description="使用SSH进行横向移动。",
        severity=Severity.HIGH,
        detection_suggestions=["监控SSH连接", "检测异常SSH登录", "启用SSH日志"],
        mitigation_suggestions=["限制SSH访问", "使用密钥认证", "实施多因素认证"],
        platforms=["Linux", "macOS"],
        data_sources=["SSH Logs", "Authentication Logs", "Network Traffic"],
    ),
    "T1021.006": AttckTechnique(
        technique_id="T1021.006",
        name="Windows Remote Management",
        tactic=AttckTactic.LATERAL_MOVEMENT,
        description="使用WinRM进行横向移动。",
        severity=Severity.HIGH,
        detection_suggestions=["监控WinRM连接", "检测异常WinRM使用", "启用WinRM日志"],
        mitigation_suggestions=["限制WinRM访问", "启用WinRM日志", "实施网络分段"],
        platforms=["Windows"],
        data_sources=["WinRM Logs", "Authentication Logs", "Network Traffic"],
    ),
    "T1550": AttckTechnique(
        technique_id="T1550",
        name="Use Alternate Authentication Material",
        tactic=AttckTactic.LATERAL_MOVEMENT,
        description="使用替代认证材料进行横向移动。",
        severity=Severity.HIGH,
        detection_suggestions=["监控替代认证使用", "检测异常认证模式", "启用认证日志"],
        mitigation_suggestions=["限制替代认证使用", "启用认证日志", "实施最小权限"],
        platforms=["Windows"],
        data_sources=["Authentication Logs", "Security Logs", "Network Traffic"],
        sub_techniques=["T1550.002", "T1550.003", "T1550.004"],
    ),
    "T1550.002": AttckTechnique(
        technique_id="T1550.002",
        name="Pass the Hash",
        tactic=AttckTactic.LATERAL_MOVEMENT,
        description="通过哈希传递(PtH)进行横向移动。",
        severity=Severity.CRITICAL,
        detection_suggestions=["监控NTLM认证异常", "检测哈希传递工具", "启用认证日志"],
        mitigation_suggestions=["禁用NTLM认证", "启用Credential Guard", "实施最小权限"],
        platforms=["Windows"],
        data_sources=["Authentication Logs", "Security Logs", "Network Traffic"],
    ),
    "T1550.003": AttckTechnique(
        technique_id="T1550.003",
        name="Pass the Ticket",
        tactic=AttckTactic.LATERAL_MOVEMENT,
        description="通过票据传递(PtT)进行横向移动。",
        severity=Severity.CRITICAL,
        detection_suggestions=["监控Kerberos票据使用", "检测异常票据请求", "启用Kerberos审计"],
        mitigation_suggestions=["限制票据请求", "启用Kerberos审计", "实施最小权限"],
        platforms=["Windows"],
        data_sources=["Kerberos Logs", "Authentication Logs", "Security Logs"],
    ),
    "T1550.004": AttckTechnique(
        technique_id="T1550.004",
        name="Web Session Cookie",
        tactic=AttckTactic.LATERAL_MOVEMENT,
        description="使用Web会话Cookie进行横向移动。",
        severity=Severity.HIGH,
        detection_suggestions=["监控Cookie窃取", "检测异常会话使用", "启用Web日志"],
        mitigation_suggestions=["启用HttpOnly标志", "实施会话管理", "启用Web日志"],
        platforms=["Windows", "Linux", "macOS"],
        data_sources=["Web Logs", "Authentication Logs", "Network Traffic"],
    ),
    "T1570": AttckTechnique(
        technique_id="T1570",
        name="Lateral Tool Transfer",
        tactic=AttckTactic.LATERAL_MOVEMENT,
        description="在横向移动过程中传输工具。",
        severity=Severity.HIGH,
        detection_suggestions=["监控文件传输行为", "检测异常文件共享", "启用文件审计"],
        mitigation_suggestions=["限制文件共享", "启用文件审计", "实施网络分段"],
        platforms=["Windows", "Linux", "macOS"],
        data_sources=["File Access", "Network Traffic", "Process Creation"],
    ),
    "T1005": AttckTechnique(
        technique_id="T1005",
        name="Data from Local System",
        tactic=AttckTactic.COLLECTION,
        description="从本地系统收集数据。",
        severity=Severity.HIGH,
        detection_suggestions=["监控敏感文件访问", "检测数据收集行为", "启用文件审计"],
        mitigation_suggestions=["实施数据分类", "启用文件审计", "实施最小权限"],
        platforms=["Windows", "Linux", "macOS"],
        data_sources=["File Access", "Process Creation"],
    ),
    "T1560": AttckTechnique(
        technique_id="T1560",
        name="Archive Collected Data",
        tactic=AttckTactic.COLLECTION,
        description="压缩收集的数据以便渗出。",
        severity=Severity.MEDIUM,
        detection_suggestions=["监控压缩工具使用", "检测异常归档行为", "启用进程审计"],
        mitigation_suggestions=["限制压缩工具使用", "启用进程审计", "实施数据防泄漏"],
        platforms=["Windows", "Linux", "macOS"],
        data_sources=["Process Creation", "File Creation"],
        sub_techniques=["T1560.001", "T1560.002"],
    ),
    "T1560.001": AttckTechnique(
        technique_id="T1560.001",
        name="Archive via Utility",
        tactic=AttckTactic.COLLECTION,
        description="使用系统工具压缩数据。",
        severity=Severity.MEDIUM,
        detection_suggestions=["监控tar/zip执行", "检测异常压缩行为", "启用进程审计"],
        mitigation_suggestions=["限制压缩工具使用", "启用进程审计", "实施数据防泄漏"],
        platforms=["Windows", "Linux", "macOS"],
        data_sources=["Process Creation", "Command Line Arguments"],
    ),
    "T1560.002": AttckTechnique(
        technique_id="T1560.002",
        name="Archive via Library",
        tactic=AttckTactic.COLLECTION,
        description="使用库压缩数据。",
        severity=Severity.MEDIUM,
        detection_suggestions=["监控库调用", "检测异常压缩行为", "启用进程审计"],
        mitigation_suggestions=["限制库访问", "启用进程审计", "实施数据防泄漏"],
        platforms=["Windows", "Linux", "macOS"],
        data_sources=["Process Creation", "API Calls"],
    ),
    "T1071": AttckTechnique(
        technique_id="T1071",
        name="Application Layer Protocol",
        tactic=AttckTactic.COMMAND_AND_CONTROL,
        description="使用应用层协议进行命令与控制。",
        severity=Severity.HIGH,
        detection_suggestions=["监控异常Web流量", "检测C2通信模式", "启用网络流量分析"],
        mitigation_suggestions=["实施网络监控", "部署IDS/IPS", "限制出站连接"],
        platforms=["Windows", "Linux", "macOS", "Network"],
        data_sources=["Network Traffic", "Proxy Logs", "DNS Logs"],
        sub_techniques=["T1071.001", "T1071.004"],
    ),
    "T1071.001": AttckTechnique(
        technique_id="T1071.001",
        name="Web Protocols",
        tactic=AttckTactic.COMMAND_AND_CONTROL,
        description="使用Web协议(HTTP/HTTPS)进行C2通信。",
        severity=Severity.HIGH,
        detection_suggestions=["监控异常HTTP流量", "检测C2通信模式", "启用代理日志"],
        mitigation_suggestions=["实施代理监控", "部署IDS/IPS", "限制出站连接"],
        platforms=["Windows", "Linux", "macOS", "Network"],
        data_sources=["Network Traffic", "Proxy Logs", "Web Logs"],
    ),
    "T1071.004": AttckTechnique(
        technique_id="T1071.004",
        name="DNS",
        tactic=AttckTactic.COMMAND_AND_CONTROL,
        description="使用DNS协议进行C2通信。",
        severity=Severity.HIGH,
        detection_suggestions=["监控异常DNS查询", "检测DNS隧道", "启用DNS日志"],
        mitigation_suggestions=["实施DNS监控", "部署DNS防火墙", "限制DNS查询"],
        platforms=["Windows", "Linux", "macOS", "Network"],
        data_sources=["DNS Logs", "Network Traffic"],
    ),
    "T1132": AttckTechnique(
        technique_id="T1132",
        name="Data Encoding",
        tactic=AttckTactic.COMMAND_AND_CONTROL,
        description="使用编码技术隐藏C2通信。",
        severity=Severity.MEDIUM,
        detection_suggestions=["监控编码数据", "检测Base64等编码", "启用网络流量分析"],
        mitigation_suggestions=["实施网络监控", "部署IDS/IPS", "启用流量分析"],
        platforms=["Windows", "Linux", "macOS", "Network"],
        data_sources=["Network Traffic", "Proxy Logs"],
        sub_techniques=["T1132.001"],
    ),
    "T1132.001": AttckTechnique(
        technique_id="T1132.001",
        name="Standard Encoding",
        tactic=AttckTactic.COMMAND_AND_CONTROL,
        description="使用标准编码（如Base64）隐藏数据。",
        severity=Severity.MEDIUM,
        detection_suggestions=["监控Base64编码数据", "检测编码通信", "启用流量分析"],
        mitigation_suggestions=["实施流量分析", "部署IDS/IPS", "启用代理监控"],
        platforms=["Windows", "Linux", "macOS", "Network"],
        data_sources=["Network Traffic", "Proxy Logs"],
    ),
    "T1573": AttckTechnique(
        technique_id="T1573",
        name="Encrypted Channel",
        tactic=AttckTactic.COMMAND_AND_CONTROL,
        description="使用加密信道进行C2通信。",
        severity=Severity.HIGH,
        detection_suggestions=["监控加密流量", "检测异常TLS连接", "启用SSL/TLS检查"],
        mitigation_suggestions=["实施SSL/TLS检查", "部署网络监控", "限制加密连接"],
        platforms=["Windows", "Linux", "macOS", "Network"],
        data_sources=["Network Traffic", "Proxy Logs", "SSL/TLS Logs"],
        sub_techniques=["T1573.001", "T1573.002"],
    ),
    "T1573.001": AttckTechnique(
        technique_id="T1573.001",
        name="Symmetric Cryptography",
        tactic=AttckTactic.COMMAND_AND_CONTROL,
        description="使用对称加密进行C2通信。",
        severity=Severity.HIGH,
        detection_suggestions=["监控加密流量", "检测对称加密模式", "启用流量分析"],
        mitigation_suggestions=["实施流量分析", "部署网络监控", "启用SSL/TLS检查"],
        platforms=["Windows", "Linux", "macOS", "Network"],
        data_sources=["Network Traffic", "Proxy Logs"],
    ),
    "T1573.002": AttckTechnique(
        technique_id="T1573.002",
        name="Asymmetric Cryptography",
        tactic=AttckTactic.COMMAND_AND_CONTROL,
        description="使用非对称加密进行C2通信。",
        severity=Severity.HIGH,
        detection_suggestions=["监控加密流量", "检测非对称加密模式", "启用流量分析"],
        mitigation_suggestions=["实施流量分析", "部署网络监控", "启用SSL/TLS检查"],
        platforms=["Windows", "Linux", "macOS", "Network"],
        data_sources=["Network Traffic", "Proxy Logs"],
    ),
    "T1041": AttckTechnique(
        technique_id="T1041",
        name="Exfiltration Over C2 Channel",
        tactic=AttckTactic.EXFILTRATION,
        description="通过C2信道渗出数据。",
        severity=Severity.CRITICAL,
        detection_suggestions=["监控C2数据上传", "检测异常数据传输", "启用网络流量分析"],
        mitigation_suggestions=["实施网络监控", "部署DLP", "限制出站连接"],
        platforms=["Windows", "Linux", "macOS", "Network"],
        data_sources=["Network Traffic", "Proxy Logs", "C2 Logs"],
    ),
    "T1048": AttckTechnique(
        technique_id="T1048",
        name="Exfiltration Over Alternative Protocol",
        tactic=AttckTactic.EXFILTRATION,
        description="通过替代协议渗出数据。",
        severity=Severity.HIGH,
        detection_suggestions=["监控异常协议使用", "检测数据渗出模式", "启用网络流量分析"],
        mitigation_suggestions=["实施网络监控", "部署DLP", "限制协议使用"],
        platforms=["Windows", "Linux", "macOS", "Network"],
        data_sources=["Network Traffic", "Proxy Logs", "Firewall Logs"],
        sub_techniques=["T1048.001", "T1048.002"],
    ),
    "T1048.001": AttckTechnique(
        technique_id="T1048.001",
        name="Exfiltration Over Symmetric Encrypted Non-C2 Protocol",
        tactic=AttckTactic.EXFILTRATION,
        description="通过对称加密的非C2协议渗出数据。",
        severity=Severity.HIGH,
        detection_suggestions=["监控加密协议使用", "检测异常数据传输", "启用流量分析"],
        mitigation_suggestions=["实施流量分析", "部署DLP", "限制协议使用"],
        platforms=["Windows", "Linux", "macOS", "Network"],
        data_sources=["Network Traffic", "Proxy Logs"],
    ),
    "T1048.002": AttckTechnique(
        technique_id="T1048.002",
        name="Exfiltration Over Asymmetric Encrypted Non-C2 Protocol",
        tactic=AttckTactic.EXFILTRATION,
        description="通过非对称加密的非C2协议渗出数据。",
        severity=Severity.HIGH,
        detection_suggestions=["监控加密协议使用", "检测异常数据传输", "启用流量分析"],
        mitigation_suggestions=["实施流量分析", "部署DLP", "限制协议使用"],
        platforms=["Windows", "Linux", "macOS", "Network"],
        data_sources=["Network Traffic", "Proxy Logs"],
    ),
    "T1486": AttckTechnique(
        technique_id="T1486",
        name="Data Encrypted for Impact",
        tactic=AttckTactic.IMPACT,
        description="加密数据以造成影响（勒索软件）。",
        severity=Severity.CRITICAL,
        detection_suggestions=["监控大量文件加密", "检测勒索软件行为", "启用文件审计"],
        mitigation_suggestions=["实施数据备份", "部署端点保护", "启用文件审计"],
        platforms=["Windows", "Linux", "macOS"],
        data_sources=["File Modification", "Process Creation", "Endpoint Detection"],
    ),
    "T1485": AttckTechnique(
        technique_id="T1485",
        name="Data Destruction",
        tactic=AttckTactic.IMPACT,
        description="破坏数据以造成影响。",
        severity=Severity.CRITICAL,
        detection_suggestions=["监控大量文件删除", "检测数据破坏行为", "启用文件审计"],
        mitigation_suggestions=["实施数据备份", "启用文件审计", "实施最小权限"],
        platforms=["Windows", "Linux", "macOS"],
        data_sources=["File Deletion", "Process Creation", "Endpoint Detection"],
    ),
}
